# 進階指引

此進階指引深入解釋軟體套件提供的基本函數，建議讀者先按照入門指南試用這些函數，才來看此進階指引，入門指南舉的例子不會有此重複。

## 安裝

用以下`pip`措令安裝及更新軟體套件。.

In [1]:
#取消註解字串#來執行措令
#pip install --upgrade ChineseCalendar_py

## 載入軟體套件

In [2]:
import ChineseCalendar_py.calendar_conversion as ccal
from IPython.display import HTML
import pandas as pd

用以下指令建立中曆物件實例。輸入參數`'ChiT'`表示函數的輸出的語言是傳統中文，其他兩個可用的參數是`'Eng'`(英文)及`'ChiS'`(簡體中文)。

In [3]:
cal = ccal.calendar_conversion('ChiT')

## 預設中曆及其他支持的中曆

中國有時處於分裂局面，各政權行用不同的曆法，本軟體在分裂時代提供多部（但非全部）同時行用的曆法。

為免混亂，如果用者沒有指明用某一特定曆法，本軟體在中國分裂時代選取了一套曆法，稱為「預設中曆」。預設中曆在春秋時代用魯國曆法（春秋曆），戰國時代用周朝曆法，三國時代用魏國曆法，東晉南北朝用南朝（東晉、宋、齊、梁、陳）曆法，五代十國用北朝（梁、唐、晉、漢、周）曆法，宋、遼、金、蒙古時期用宋朝曆法，南明、明鄭、清時期用清朝曆法，詳情可參閱[預設中曆網頁](https://ytliu0.github.io/ChineseCalendar-python/tutorial/traditional_Chinese/default_calendar.html)，預設中曆的年限是-721年至2200年。

如[預設中曆網頁](https://ytliu0.github.io/ChineseCalendar-python/tutorial/traditional_Chinese/default_calendar.html)所述，-103年至2200年的中曆用查表法獲取，這段時期中曆的朔閏及曆書節氣數據存於源碼文件夾'src/ChineseCalendar_py/'的'default_calendar_M105_2201.csv'檔案中，曆日以距公曆年1月0日的日數表示。當中曆物件實例建立時，檔案中的朔閏數據載入 numpy array `.calData`，曆書節氣數據載入 numpy array `.calSterm`。在這資料夾的日曆計算習題 notebook 中會有實例展示這兩個 numpy array 在某些計算上很有用。為了方便計算日曆，這兩個 numpy array 的曆日資料其實涵蓋-105年至2202年。

除了預設中曆外，本軟體還提供一些其他的中曆，詳情可參閱[其他中曆網頁](https://ytliu0.github.io/ChineseCalendar-python/tutorial/traditional_Chinese/available_calendars.html)。網頁中列出的所有中曆都有行用年份，大多數中曆用其曆法法則計算，原則上可用於行用年份之外，但這裡極不鼓勵用者如此做。

## 公曆轉中曆

本軟體套件提供下列三個函數轉公曆為中曆：

- `.western_to_chinese_date(y, m, d, calendar='default', multiple_calendars=False, ephemeris='None')`: 公曆日期(年 = y, 月 = m, 日 = d)轉中曆日期。

- `.western_to_chinese_year(y, m=None, calendar='default', ephemeris='None')`: 公曆 y 年 m 月 中所有日期轉為中曆日期。如果 m 是 None，則將公曆年 y 中所有日期轉為中曆日期。

- `.western_to_chinese_year_html(y, m=None, calendar='default', showJDN=False, ephemeris='None', show_chinese_year_info=True,show_chinese_calendar_info=True)`: 與函數`.western_to_chinese_year(y, m=None, calendar='default', ephemeris='None')`的功能一樣，但會輸出 HTML 格式的文字。

`calendar`參數用來選取某中曆，默認值是'default'，表示預設中曆，用者可選擇[其他中曆網頁](https://ytliu0.github.io/ChineseCalendar-python/tutorial/traditional_Chinese/available_calendars.html)列出的中曆標記選擇其他中曆。

`multiple_calendars`參數只有當`calendar`參數是'default'(預設中曆)時才有作用。如果`multiple_calendars`設定為`True`，分裂時代的輸出中曆會列出多個當時行用的中曆。

`ephemeris`參數讓用者選擇用哪個現代曆表計算月相和節氣時刻，這裡只支持'DE431'和'DE441'，默認值是'None'，表示會用已設定的曆表，如果還未設定曆表，則用默認值'DE441'。

以下指令轉公曆445年2月25日為北魏行用的曆法。根據[其他中曆網頁](https://ytliu0.github.io/ChineseCalendar-python/tutorial/traditional_Chinese/available_calendars.html)，北魏的日曆要用 'WeiZhouSui' 標記。

In [4]:
cal.western_to_chinese_date(445, 2, 25, calendar='WeiZhouSui')

{'Western ymd': [445, 2, 25],
 'Western calendar': '儒略曆',
 'JDN': 1883650,
 'Chinese ymd': [445, -1, 3],
 'cyear': 445,
 'cdate': '閏正月初三',
 'sexagenary year': ['乙酉', '雞', 22],
 'Nday_cmonth': 29,
 'sexagenary date': ['癸亥', 60],
 'Week': ['星期日', 0],
 'period': '南北朝 (420 - 580)',
 'reign/era': '北魏太武帝太平真君六年',
 'Chinese calendar': '景初曆'}

函數輸出顯示公曆445年2月25日，在北魏的日曆是太武帝太平真君六年閏正月初三，年干支是乙酉、日干支是癸亥，當時北魏行用的曆法是景初曆。

此函數的輸出是 python dictionary，有下列的字典鍵(keys):

`'Western ymd'`: python list 包含公曆的年月日。

`'Western calendar'`: 公曆版本 (格里曆、儒略曆或逆推儒略曆)。

`'JDN'`: 正午儒略日數。

`'Chinese ymd'`: 包含中曆的年月日，閏月的月份用負數表示。 

`'cyear'`: 與中曆年日期重疊最多的公曆年份，也是`'Chinese ymd'` list 中第一個數字。此例的太平真君六年就是445年，因為太平真君六年始於445年1月24日，終於446年2月11日，太平真君六年與公曆445年有342日重疊，是重疊日數最多的公曆年，因此甲辰年的`'cyear'`取445。

`'cdate'`: 中曆日期。

`'sexagenary year'`: python list 顯示年干支，年地支對應的生肖，及干支數 (1=甲子，2＝乙丑，3＝丙寅等，六十干支的干支數可參閱[干支網頁](https://ytliu0.github.io/ChineseCalendar/sexagenary_chinese.html)的表二) 。

`'jian'`: 中曆月的月建干支，月干支的詳情可參閱[干支網頁](https://ytliu0.github.io/ChineseCalendar/sexagenary_chinese.html)。

`'Nday_cmonth'`: 中曆月的日數，一般是29日或30日。

`'sexagenary date'`: 日干支及其干支數，日干支的詳情參閱[干支網頁](https://ytliu0.github.io/ChineseCalendar/sexagenary_chinese.html)。

`'Week'`: 星期及星期數，星期數用 0、1、2、3、4、5、6 表示星期日、一、二、三、四、五、六。 

`'period'`: 中國歷史的時代。

`'Chinese calendar'`: 中曆的版本。

與我的[農曆網站](https://ytliu0.github.io/ChineseCalendar/index_chinese.html)一樣，公曆年 y 的年限是 -721 至 2200。當中國處於分裂時代時常有多個曆法同時使用，這裡用的指令只提供其中一個版本，其他版本的日期也可以獲取，方法是選'calendar'參數為'default'及'multiple_calendars'為True:

In [5]:
cal.western_to_chinese_date(445, 2, 25, multiple_calendars=True)

[{'Western ymd': [445, 2, 25],
  'Western calendar': '儒略曆',
  'JDN': 1883650,
  'Chinese ymd': [445, 2, 3],
  'cyear': 445,
  'cdate': '二月初三',
  'sexagenary year': ['乙酉', '雞', 22],
  'jian': ['建己卯', 16],
  'Nday_cmonth': 29,
  'sexagenary date': ['癸亥', 60],
  'Week': ['星期日', 0],
  'period': '南北朝 (420 - 580)',
  'reign/era': '宋文帝元嘉二十二年',
  'Chinese calendar': '元嘉曆'},
 {'Western ymd': [445, 2, 25],
  'Western calendar': '儒略曆',
  'JDN': 1883650,
  'Chinese ymd': [445, -1, 3],
  'cyear': 445,
  'cdate': '閏正月初三',
  'sexagenary year': ['乙酉', '雞', 22],
  'Nday_cmonth': 29,
  'sexagenary date': ['癸亥', 60],
  'Week': ['星期日', 0],
  'period': '南北朝 (420 - 580)',
  'reign/era': '北魏太武帝太平真君六年',
  'Chinese calendar': '景初曆'}]

此輸出顯示公曆445年2月25日在劉宋的曆法是文帝元嘉二十二年二月初三，當時宋朝行用的曆法是元嘉曆，此日期就是預設中曆輸出的日期。

指令`cal.western_to_chinese_year(445, 2, calendar='WeiZhouSui')`輸出 python list 包含公曆445年2月對應的北魏曆法日期；`cal.western_to_chinese_year(445, calendar='WeiZhouSui')` 則輸出 python list 包含公曆445年全年對應的北魏曆法日期。

In [6]:
cal.western_to_chinese_year(445, 2, calendar='WeiZhouSui')

[{'Western ymd': [445, 2, 1],
  'Western calendar': '儒略曆',
  'JDN': 1883626,
  'Chinese ymd': [445, 1, 9],
  'cyear': 445,
  'cdate': '正月初九',
  'sexagenary year': ['乙酉', '雞', 22],
  'jian': ['建戊寅', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['己亥', 36],
  'Week': ['星期四', 4],
  'period': '南北朝 (420 - 580)',
  'reign/era': '北魏太武帝太平真君六年',
  'Chinese calendar': '景初曆'},
 {'Western ymd': [445, 2, 2],
  'Western calendar': '儒略曆',
  'JDN': 1883627,
  'Chinese ymd': [445, 1, 10],
  'cyear': 445,
  'cdate': '正月初十',
  'sexagenary year': ['乙酉', '雞', 22],
  'jian': ['建戊寅', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['庚子', 37],
  'Week': ['星期五', 5],
  'period': '南北朝 (420 - 580)',
  'reign/era': '北魏太武帝太平真君六年',
  'Chinese calendar': '景初曆'},
 {'Western ymd': [445, 2, 3],
  'Western calendar': '儒略曆',
  'JDN': 1883628,
  'Chinese ymd': [445, 1, 11],
  'cyear': 445,
  'cdate': '正月十一',
  'sexagenary year': ['乙酉', '雞', 22],
  'jian': ['建戊寅', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['辛丑', 38],
 

以上的輸出如果用於其後的日曆計算或許有用，但對於瀏覽來說並不是很方便，函數`.western_to_chinese_year_html()`輸出的 HTML 文字用`IPython.display.HTML()`的函數處理後，就會得到如[這農曆網頁](https://ytliu0.github.io/ChineseCalendar/index_chinese.html)的表列顯示，比較方便瀏覽。

In [7]:
# 公曆445年2月與北魏日曆對照
HTML(cal.western_to_chinese_year_html(445, 2, calendar='WeiZhouSui'))

In [8]:
# 顯示445年2月的北魏月曆，並顯示每日的正午儒略日數。
HTML(cal.western_to_chinese_year_html(445, 2, calendar='WeiZhouSui', showJDN=True))

上面列出的月相和二十四節氣如[農曆網站](https://ytliu0.github.io/ChineseCalendar/index_chinese.html)的一樣是指用現代方法以噴射推進實驗室的 DE441 曆表算出，而曆書節氣指按當時中國曆法算出的節氣日期。

中國科學院紫金山天文臺從 2014年起用 DE421 曆表編算天文年曆，直至2025年還沒有更新曆表，不過 DE421 算出的月相和節氣時刻與 DE431/DE441 在現代相差甚微。所有用現代曆表算出的月相和節氣時刻都用東八區時間 UT+8 (UT 在1972年前指 UT1， 1972年到今年指 UTC，未來年份則是預推的 UTC)。

In [9]:
# 用國標 《農曆的編算和頒行》 GB/T 33661-2017 算出的2500年年曆
HTML(cal.western_to_chinese_year_html(2500, calendar='GBT'))

## 中曆轉公曆

本軟體提供以下四個函數可用來轉中曆為公曆：

`.chinese_to_western_date(y, m, d, calendar='default', ephemeris='None')`: 轉中曆年月日 y, m, d 為公曆日期，閏月的 m 值為負數。

`.chinese_year_info(y, calendar='default', ephemeris='None')`: 函數輸出中曆年 y 的所有中曆月初一的公曆日期，曆書節氣，及用現代曆表 (DE431 或 DE441) 算出的節氣。

`.chinese_year_html(y, calendar='default', ephemeris='None')`: 與上述函數的功能一致，但輸出 HTML 文字。

`.chinese_to_western_year(y, m=None, calendar='default', ephemeris='None')`: 列出中曆年 y 中曆月 m 所有日期的公曆日期。如果 m 是 None，則列出中曆年全年的公曆日期。

`chinese_to_western_year_html(y, m=None, calendar='default', showJDN=False, ephemeris='None', show_chinese_year_info=True, show_chinese_calendar_info=True)`: 與上述函數的功能一致，但輸出 HTML 文字。

我的[農曆網站](https://ytliu0.github.io/ChineseCalendar/index_chinese.html) 並沒有網頁列出這些函數提供的公曆資料，[朔閏表網頁](https://ytliu0.github.io/ChineseCalendar/table_chinese.html)提供與`.chinese_year_html()`函數相近的資料。

這些函數的用法與公曆轉中曆的函數接近，茲舉例展示。

In [10]:
# 轉南明永曆十五年(1661年)八月十五日為公曆
cal.chinese_to_western_date(1661, 8, 15, calendar='SouthernMing')

{'Chinese ymd': [1661, 8, 15],
 'Western ymd': [1661, 9, 8],
 'Western calendar': '格里曆',
 'JDN': 2327979,
 'cyear': 1661,
 'cdate': '八月十五',
 'sexagenary year': ['辛丑', '牛', 38],
 'jian': ['建丁酉', 34],
 'Nday_cmonth': 29,
 'sexagenary date': ['壬辰', 29],
 'Week': ['星期四', 4],
 'period': '清 (1645 - 1911)',
 'reign/era': '南明永曆十五年',
 'Chinese calendar': '殘明大統曆'}

輸出顯示公曆日期是1661年9月8日。注意南明的八月十五在這年與清朝時憲曆不一致，清世祖順治十八年八月十五在1661年10月7日，可用`cal.chinese_to_western_date(1661, 8, 15)`驗證。

歷代中國因曆法改革有時會出現中曆日期對應兩個公曆日期的情況，例如762年的五月十二日：

In [11]:
cal.chinese_to_western_date(762, 5, 12)

[{'Chinese ymd': [762, 5, 12],
  'Western ymd': [762, 4, 10],
  'Western calendar': '儒略曆',
  'JDN': 1999478,
  'cyear': 762,
  'cdate': '五月十二',
  'sexagenary year': ['壬寅', '虎', 39],
  'jian': ['建甲辰', 41],
  'Nday_cmonth': 30,
  'sexagenary date': ['辛卯', 28],
  'Week': ['星期六', 6],
  'period': '唐 (618 - 907)',
  'reign/era': '唐肅宗上元三年/寶應元年',
  'Chinese calendar': '五紀曆'},
 {'Chinese ymd': [762, 5, 12],
  'Western ymd': [762, 6, 8],
  'Western calendar': '儒略曆',
  'JDN': 1999537,
  'cyear': 762,
  'cdate': '五月十二',
  'sexagenary year': ['壬寅', '虎', 39],
  'jian': ['建丙午', 43],
  'Nday_cmonth': 30,
  'sexagenary date': ['庚寅', 27],
  'Week': ['星期二', 2],
  'period': '唐 (618 - 907)',
  'reign/era': '唐肅宗上元三年/寶應元年',
  'Chinese calendar': '五紀曆'}]

以下指令顯示顓頊曆-250年(前251年)的曆日資料。

In [12]:
cal.chinese_year_info(-250, calendar='Zhuanxu')

{'cm': [{'cm': 10, 'JDN': 1629685, 'jian': 'NA', 'n': 29},
  {'cm': 11, 'JDN': 1629714, 'jian': 'NA', 'n': 30},
  {'cm': 12, 'JDN': 1629744, 'jian': 'NA', 'n': 29},
  {'cm': 1, 'JDN': 1629773, 'jian': 'NA', 'n': 30},
  {'cm': 2, 'JDN': 1629803, 'jian': 'NA', 'n': 29},
  {'cm': 3, 'JDN': 1629832, 'jian': 'NA', 'n': 30},
  {'cm': 4, 'JDN': 1629862, 'jian': 'NZ', 'n': 29},
  {'cm': 5, 'JDN': 1629891, 'jian': 'NA', 'n': 30},
  {'cm': 6, 'JDN': 1629921, 'jian': 'NA', 'n': 30},
  {'cm': 7, 'JDN': 1629951, 'jian': 'NA', 'n': 29},
  {'cm': 8, 'JDN': 1629980, 'jian': 'NA', 'n': 30},
  {'cm': 9, 'JDN': 1630010, 'jian': 'NA', 'n': 29},
  {'cm': -9, 'JDN': 1630039, 'jian': 'NA', 'n': 30}],
 'calendar': '顓頊曆',
 'reign/era': '秦昭襄王五十六年',
 'calst': [('J10', 1629693),
  ('Z10', 1629708),
  ('J11', 1629723),
  ('Z11', 1629739),
  ('J12', 1629754),
  ('Z12', 1629769),
  ('J1', 1629784),
  ('Z1', 1629799),
  ('J2', 1629815),
  ('Z2', 1629830),
  ('J3', 1629845),
  ('Z3', 1629860),
  ('J4', 1629876),
  ('Z

此函數輸出 python dictionary，有以下字鍵：

`'cm'`: python list 含有以下中曆資料： \[{'cm':m1, 'JDN':JDN1, 'jian':'jian1', 'n':n1}, {'cm':m2, 'JDN':JDN2, 'jian':'jian2', 'n':n2}, ...\]，'cm' 表示中曆月序(負數表示閏月), 'JDN' 表示朔日的正午儒略日數， 'jian' 表示用月建來算的月干支數 ('jian'='1' 表示甲子，'2' 表示乙丑，⋯⋯，'60' 表示癸亥，'NA' 表示中曆月沒有月建，一般是閏月，但-103年以前的曆法因不用無中氣置閏也不列月建，'NZ' 表示此月不含中氣，這只適用於古六曆的月份)，'n' 表示中曆月的日數。 此 python list 以 'JDN' 的數值由小至大排序。

`'calendar'`: 中曆的版本 (例如 '三統曆'， '時憲曆' 等)。

`'reign/era'` (只適用於 1912年前的年份): 中曆年的年號或皇帝紀年。

`'calst'`: 曆書節氣 tuples \[(lab1, jdn1), (lab2, jdn2), ...\]， lab1, lab2, ... 是曆書節氣的標記，例如 'J1' 表示正月節(立春)，'Z4' 表示四月中(小滿) 等，jdn1, jdn2, ... 是曆書節氣的正午儒略日數。

`'datongST'` (只適用於預設中曆在1667至1669的中曆年): 用大統曆算出的節氣 \[(lab1, jdn1), (lab2, jdn2), ...\]。康熙六年(1667)至八年(1669)清朝因曆獄而復用明朝《大統曆》，但後來清朝欽天監編的《御定萬年書》試圖抹去這段歷史，用時憲曆追推這幾年的節氣，但臺灣國立故宮博物院的清代檔案檢索系統藏有這幾年的《大清七政經緯躔度時憲曆》，顯示這幾年的節氣日期確是符合大統曆的推算，而不符合時憲曆的推算，所以此處在這幾年列出大統曆的節氣。

`'sterm'`: python list \[\[lab1, info1\], \[lab2, info2\], ...\] 顯示用 DE431/DE441曆表算出的節氣，lab1, lab2, ... 為節氣標記，info1, info2, ... 則是 python dictionary，顯示節氣的日期及 UT+8 時刻。

`'mphase'`: python list \[\[lab1, info1\], \[lab2, info2\], ...\] 顯示用 DE431/DE441 曆表算出的中曆年內所有的月相資料。lab1, lab2, ... 是月相的標記： 'Q0' 是朔，'Q1' 是上弦，'Q2' 是望，'Q3' 是下弦。 info1, info2, ... 是 python dictionary，顯示月相的日期及 UT+8 時刻。

此函數輸出的 python list 不方便瀏覽， 函數 `.chinese_year_info_html()` 輸出 HTML 文字，可用 `IPython.display.HTML()` 函數將資料以表格形式顯示。

In [13]:
# 顓頊曆-250年(前251年)的曆日資料
HTML(cal.chinese_year_html(-250, calendar='Zhuanxu'))

中曆月,朔日,曆書節氣,DE441節氣 (UT+8)
十月小,戊寅11月1日,立冬: 初九 (11月9日)小雪: 廿四 (11月24日),立冬: 十一 (11月11日) 00:05小雪: 廿五 (11月25日) 17:02
十一月大,丁未11月30日,大雪: 初十 (12月9日)冬至: 廿六 (12月25日),大雪: 十一 (12月10日) 09:34冬至: 廿六 (12月25日) 02:50
十二月小,丁丑12月30日,小寒: 十一 (1月9日)大寒: 廿六 (1月24日),小寒: 初十 (1月8日) 21:19大寒: 廿五 (1月23日) 18:03
正月大,丙午1月28日,立春: 十二 (2月8日)雨水: 廿七 (2月23日),立春: 十一 (2月7日) 17:18雨水: 廿六 (2月22日) 19:49
二月小,丙子2月27日,驚蟄: 十三 (3月11日)春分: 廿八 (3月26日),驚蟄: 十二 (3月10日) 01:30春分: 廿七 (3月25日) 10:39
三月大,乙巳3月28日,清明: 十四 (4月10日)穀雨: 廿九 (4月25日),清明: 十三 (4月9日) 22:47穀雨: 廿九 (4月25日) 13:37
四月小(無中氣),乙亥4月27日,立夏: 十五 (5月11日),立夏: 十五 (5月11日) 06:22
五月大,甲辰5月26日,小滿: 初一 (5月26日)芒種: 十六 (6月10日),小滿: 初二 (5月27日) 00:18芒種: 十七 (6月11日) 18:30
六月大,甲戌6月25日,夏至: 初一 (6月25日)小暑: 十六 (7月10日),夏至: 初三 (6月27日) 12:01小暑: 十九 (7月13日) 04:05
七月小,甲辰7月25日,大暑: 初二 (7月26日)立秋: 十七 (8月10日),大暑: 初四 (7月28日) 17:47立秋: 二十 (8月13日) 04:47


In [14]:
# 用國標《農曆的編算與頒行》 GB/T 33661-2017 算出的2714年中曆
HTML(cal.chinese_year_html(2714, calendar='GBT'))

中曆月,朔日,曆書節氣,DE441節氣 (UT+8)
正月小建丙寅,戊午2月7日,雨水: 十三 (2月19日)驚蟄: 廿八 (3月6日),雨水: 十三 (2月19日) 21:34驚蟄: 廿八 (3月6日) 18:01
二月大建丁卯,丁亥3月8日,春分: 十四 (3月21日)清明: 廿九 (4月5日),春分: 十四 (3月21日) 16:43清明: 廿九 (4月5日) 18:15
三月小建戊辰,丁巳4月7日,穀雨: 十四 (4月20日),穀雨: 十四 (4月20日) 22:46
四月小建己巳,丙戌5月6日,立夏: 初一 (5月6日)小滿: 十六 (5月21日),立夏: 初一 (5月6日) 06:27小滿: 十六 (5月21日) 17:04
五月大建庚午,乙卯6月4日,芒種: 初三 (6月6日)夏至: 十八 (6月21日),芒種: 初三 (6月6日) 06:19夏至: 十八 (6月21日) 21:40
六月小建辛未,乙酉7月4日,小暑: 初四 (7月7日)大暑: 二十 (7月23日),小暑: 初四 (7月7日) 14:20大暑: 二十 (7月23日) 07:41
七月大建壬申,甲寅8月2日,立秋: 初七 (8月8日)處暑: 廿二 (8月23日),立秋: 初七 (8月8日) 00:38處暑: 廿二 (8月23日) 16:38
八月大建癸酉,甲申9月1日,白露: 初八 (9月8日)秋分: 廿三 (9月23日),白露: 初八 (9月8日) 06:37秋分: 廿三 (9月23日) 18:20
九月小建甲戌,甲寅10月1日,寒露: 初九 (10月9日)霜降: 廿四 (10月24日),寒露: 初九 (10月9日) 03:00霜降: 廿四 (10月24日) 08:45
十月大建乙亥,癸未10月30日,立冬: 初十 (11月8日)小雪: 廿五 (11月23日),立冬: 初十 (11月8日) 11:15小雪: 廿五 (11月23日) 11:03


In [15]:
# 遼穆宗應曆五年(955年)八月的所有日期
cal.chinese_to_western_year(955, 8, calendar='LiaoJinYuan')

[{'Chinese ymd': [955, 8, 1],
  'Western ymd': [955, 8, 20],
  'Western calendar': '儒略曆',
  'JDN': 2070103,
  'cyear': 955,
  'cdate': '八月初一',
  'sexagenary year': ['乙卯', '兔', 52],
  'jian': ['建乙酉', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['丙申', 33],
  'Week': ['星期一', 1],
  'period': '五代 (907 - 959)',
  'reign/era': '遼穆宗應曆五年',
  'Chinese calendar': '調元曆'},
 {'Chinese ymd': [955, 8, 2],
  'Western ymd': [955, 8, 21],
  'Western calendar': '儒略曆',
  'JDN': 2070104,
  'cyear': 955,
  'cdate': '八月初二',
  'sexagenary year': ['乙卯', '兔', 52],
  'jian': ['建乙酉', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['丁酉', 34],
  'Week': ['星期二', 2],
  'period': '五代 (907 - 959)',
  'reign/era': '遼穆宗應曆五年',
  'Chinese calendar': '調元曆'},
 {'Chinese ymd': [955, 8, 3],
  'Western ymd': [955, 8, 22],
  'Western calendar': '儒略曆',
  'JDN': 2070105,
  'cyear': 955,
  'cdate': '八月初三',
  'sexagenary year': ['乙卯', '兔', 52],
  'jian': ['建乙酉', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['戊戌', 35],
  'Week': 

In [16]:
# 遼穆宗應曆五年(955年)八月的 HTML 月曆表
HTML(cal.chinese_to_western_year_html(955, 8, calendar='LiaoJinYuan'))

`.western_to_chinese_year_html()`函數輸出的月相和節氣是公曆日期，此數輸出的則是中曆日期。

In [17]:
# 蜀後主延熙十七年(254年)的年曆表
HTML(cal.chinese_to_western_year_html(254, calendar='Shu'))

## 月相和二十四節氣

`ChineseCalendar_py.sunMoon.sunMoon` class 提供用現代曆表算出的月相和二十四節氣的 UT+8 日期和時刻，以下指令建立這 class 的實體。

In [18]:
sm = ccal.sunMoon.sunMoon('ChiT')

第一個輸入參數 'ChiT' 表示輸出的語言是傳統中文，其他可選的是 'Eng'(英文)和 'ChiS' (簡體中文)。

第二個可輸入的參數是 'DE431' 或 'DE441'， 表示計算月相和節氣用的曆表，默認值是 'DE441'。如前述，紫金山天文臺自2014年起用 DE421 曆表編算天文年曆，直至2025年仍是如此，DE421、DE431及DE441曆表算出的月相和節氣在距今幾十年間差異甚微(DE421 曆表的年限是1899年至2053年)，在遠古和遙遠將來 DE431 和 DE441 算出的時刻雖然差異較大，但仍未超出 TDB 轉換 UT1 的估計誤差。1929年至2013年中曆的月相和節氣用舊曆表計算，與 DE 曆表的差異可達半分鐘。1929年前的節氣不但用舊曆表計算，時刻也不用UT+8，差異當然更大。

-3502-3503月相與節氣的TDB時刻已預先算好，數據存於源碼資料夾`src/ChineseCalendar_py/sunMoon_DE431.csv`和`src/ChineseCalendar_py/sunMoon_DE441.csv`。在源碼資料夾`src/ChineseCalendar_py/`有函數`get_dTT_UT()`輸出 TT-UT 的數值，用於轉月相和節氣時刻為UT+8，此函數大約一年要更新一次以含括最新閏秒數據，因閏秒將於2035年或更早會被取消，到時便不用頻繁更新。

In [19]:
# 獲取公元3500年的節氣和月相
st, mp = sm.st_mp(3500)
print('節氣:\n', st)
print('月相:\n', mp)

節氣:
 [['J12', {'event': '小寒', 'year': 3500, 'month': 1, 'date': 6, 'hour': 7, 'minute': 2, 'dateString': '1月6日', 'timeString': '07:02', 'jd0_ut': 2999407.5, 'jd1_ut': 5.959842061353328}], ['Z12', {'event': '大寒', 'year': 3500, 'month': 1, 'date': 21, 'hour': 1, 'minute': 14, 'dateString': '1月21日', 'timeString': '01:14', 'jd0_ut': 2999407.5, 'jd1_ut': 20.718280931005655}], ['J1', {'event': '立春', 'year': 3500, 'month': 2, 'date': 4, 'hour': 18, 'minute': 54, 'dateString': '2月4日', 'timeString': '18:54', 'jd0_ut': 2999407.5, 'jd1_ut': 35.454193554548816}], ['Z1', {'event': '雨水', 'year': 3500, 'month': 2, 'date': 19, 'hour': 12, 'minute': 59, 'dateString': '2月19日', 'timeString': '12:59', 'jd0_ut': 2999407.5, 'jd1_ut': 50.20746779877934}], ['J2', {'event': '驚蟄', 'year': 3500, 'month': 3, 'date': 6, 'hour': 8, 'minute': 1, 'dateString': '3月6日', 'timeString': '08:01', 'jd0_ut': 2999407.5, 'jd1_ut': 65.00048394186084}], ['Z2', {'event': '春分', 'year': 3500, 'month': 3, 'date': 21, 'hour': 4, 'min

In [20]:
# 公元3500年的全年的月相和節氣，轉為 pandas dataframe 來顯示。
st, mp = sm.st_mp_df(3500)
display(st)
display(mp)

,節氣,時刻 (UT+8)
0,小寒,"1月6日, 07:02"
1,大寒,"1月21日, 01:14"
2,立春,"2月4日, 18:54"
3,雨水,"2月19日, 12:59"
4,驚蟄,"3月6日, 08:01"
5,春分,"3月21日, 04:53"
6,清明,"4月5日, 03:57"
7,穀雨,"4月20日, 05:50"
8,立夏,"5月5日, 10:38"
9,小滿,"5月20日, 18:32"


,朔,上弦,望,下弦
0,,"1月1日, 00:36","1月9日, 03:40<br /><a href=""http://ytliu.epizy.c...","1月17日, 01:05"
1,"1月23日, 17:03","1月30日, 17:13","2月7日, 22:50","2月15日, 12:02"
2,"2月22日, 04:24","3月1日, 12:54","3月9日, 15:55","3月16日, 20:48"
3,"3月23日, 16:24","3月31日, 09:59","4月8日, 06:10","4月15日, 04:01"
4,"4月22日, 05:25","4月30日, 06:15","5月7日, 17:43","5月14日, 10:39"
5,"5月21日, 19:42","5月29日, 23:57","6月6日, 03:04<br /><a href=""http://ytliu.epizy.c...","6月12日, 17:47"
6,"6月20日, 11:01<br /><a href=""http://ytliu.epizy....","6月28日, 14:21","7月5日, 10:52","7月12日, 02:33"
7,"7月20日, 02:39","7月28日, 01:35","8月3日, 17:50","8月10日, 13:55"
8,"8月18日, 17:49","8月26日, 10:14","9月2日, 00:56","9月9日, 04:21"
9,"9月17日, 08:03","9月24日, 17:04","10月1日, 09:19","10月8日, 21:42"


月相中朔和望還提供日月食的資料，有連結到我製的日月食網頁，要恰當顯示連結，可用 pandas dataframe 提供的 `.to_html` 函數轉為 HTML 文字，然後用 `IPython.display.HTML()` 顯示，得出的輸出類此[氣朔網頁](https://ytliu0.github.io/ChineseCalendar/sunMoon_chinese.html)的表格。

In [21]:
HTML(mp.to_html(
    render_links=True,
    escape=False,
))

,朔,上弦,望,下弦
0,,"1月1日, 00:36","1月9日, 03:40半影月食","1月17日, 01:05"
1,"1月23日, 17:03","1月30日, 17:13","2月7日, 22:50","2月15日, 12:02"
2,"2月22日, 04:24","3月1日, 12:54","3月9日, 15:55","3月16日, 20:48"
3,"3月23日, 16:24","3月31日, 09:59","4月8日, 06:10","4月15日, 04:01"
4,"4月22日, 05:25","4月30日, 06:15","5月7日, 17:43","5月14日, 10:39"
5,"5月21日, 19:42","5月29日, 23:57","6月6日, 03:04月偏食","6月12日, 17:47"
6,"6月20日, 11:01日環食","6月28日, 14:21","7月5日, 10:52","7月12日, 02:33"
7,"7月20日, 02:39","7月28日, 01:35","8月3日, 17:50","8月10日, 13:55"
8,"8月18日, 17:49","8月26日, 10:14","9月2日, 00:56","9月9日, 04:21"
9,"9月17日, 08:03","9月24日, 17:04","10月1日, 09:19","10月8日, 21:42"


## 曆書節氣

古代的節氣用當時的曆法計算，算出的節氣與用現代曆表的節氣常有大差異，函數`.calendrical_solar_terms(y, calendar='default', ephemeris='None')`提供公曆 y 年的曆書節氣，即按當時曆法計算的節氣。參數`ephemeris`只有當選取 calendar='GBT' 時用來選擇DE曆表，其他的calendar選項沒有作用。

In [22]:
# 吳大帝赤烏十三年(250年)的曆書節氣
cal.calendrical_solar_terms(250, calendar='Wu')

[{'節氣': '小寒', '日期': '1月8日'},
 {'節氣': '大寒', '日期': '1月23日'},
 {'節氣': '立春', '日期': '2月7日'},
 {'節氣': '雨水', '日期': '2月22日'},
 {'節氣': '驚蟄', '日期': '3月9日'},
 {'節氣': '春分', '日期': '3月25日'},
 {'節氣': '清明', '日期': '4月9日'},
 {'節氣': '穀雨', '日期': '4月24日'},
 {'節氣': '立夏', '日期': '5月9日'},
 {'節氣': '小滿', '日期': '5月25日'},
 {'節氣': '芒種', '日期': '6月9日'},
 {'節氣': '夏至', '日期': '6月24日'},
 {'節氣': '小暑', '日期': '7月9日'},
 {'節氣': '大暑', '日期': '7月24日'},
 {'節氣': '立秋', '日期': '8月9日'},
 {'節氣': '處暑', '日期': '8月24日'},
 {'節氣': '白露', '日期': '9月8日'},
 {'節氣': '秋分', '日期': '9月23日'},
 {'節氣': '寒露', '日期': '10月9日'},
 {'節氣': '霜降', '日期': '10月24日'},
 {'節氣': '立冬', '日期': '11月8日'},
 {'節氣': '小雪', '日期': '11月23日'},
 {'節氣': '大雪', '日期': '12月8日'},
 {'節氣': '冬至', '日期': '12月24日'}]

In [23]:
# 吳大帝赤烏十三年(250年)的曆書節氣轉為 pandas dataframe 顯示
display(pd.DataFrame(cal.calendrical_solar_terms(250, calendar='Wu')))

,節氣,日期
0,小寒,1月8日
1,大寒,1月23日
2,立春,2月7日
3,雨水,2月22日
4,驚蟄,3月9日
5,春分,3月25日
6,清明,4月9日
7,穀雨,4月24日
8,立夏,5月9日
9,小滿,5月25日


此函數輸出公曆 y 年的曆書節氣，如要中曆 y 年的曆書節氣，可用上述
`.chinese_year_info()` 或 `.chinese_year_html()` 函數。

## 日曆計算習題

上面介紹了本軟體套件提供的公曆-中曆互轉基本函數。本資料夾中`calendar_exercises.ipynb`筆記本會展示如何用本軟體提供的函數處理較複雜的日曆計算。