# 进阶指引

此进阶指引深入解释软体套件提供的基本函数，建议读者先按照入门指南试用这些函数，才来看此进阶指引，入门指南举的例子不会有此重复。

## 安装

用以下`pip`措令安装及更新软体套件。.

In [1]:
#取消注解字串#来执行措令
#pip install --upgrade ChineseCalendar_py

## 载入软体套件

In [2]:
import ChineseCalendar_py.calendar_conversion as ccal
from IPython.display import HTML
import pandas as pd

用以下措令建立中历物件实例。输入参数`'ChiS'`表示函数的输出的语言是简体中文，其他两个可用的参数是`'Eng'`(英文)及`'ChiT'`(传统中文)。

In [3]:
cal = ccal.calendar_conversion('ChiS')

## 预设中历及其他支持的中历

中国有时处于分裂局面，各政权行用不同的历法，本软体在分裂时代提供多部（但非全部）同时行用的历法。

为免混乱，如果用者没有指明用某一特定历法，本软体在中国分裂时代选取了一套历法，称为「预设中历」。预设中历在春秋时代用鲁国历法（春秋历），战国时代用周朝历法，三国时代用魏国历法，东晋南北朝用南朝（东晋、宋、齐、梁、陈）历法，五代十国用北朝（梁、唐、晋、汉、周）历法，宋、辽、金、蒙古时期用宋朝历法，南明、明郑、清时期用清朝历法，详情可参阅[预设中历网页](https://ytliu0.github.io/ChineseCalendar-python/tutorial/simplified_Chinese/default_calendar.html)，预设中历的年限是-721年至2200年。

如[预设中历网页](https://ytliu0.github.io/ChineseCalendar-python/tutorial/simplified_Chinese/default_calendar.html)所述，-103年至2200年的中历用查表法获取，这段时期中历的朔闰及历书节气数据存于源码文件夹'src/ChineseCalendar_py/'的'default_calendar_M105_2201.csv'档案中，历日以距公历年1月0日的日数表示。当中历物件实例建立时，档案中的朔闰数据载入 numpy array `.calData`，历书节气数据载入 numpy array `.calSterm`。在这资料夹的日历计算习题 notebook 中会有实例展示这两个 numpy array 在某些计算上很有用。为了方便计算日历，这两个 numpy array 的历日资料其实涵盖-105年至2202年。

除了预设中历外，本软体还提供一些其他的中历，详情可参阅[其他中历网页](https://ytliu0.github.io/ChineseCalendar-python/tutorial/simplified_Chinese/available_calendars.html)。网页中列出的所有中历都有行用年份，大多数中历用其历法法则计算，原则上可用于行用年份之外，但这里极不鼓励用者如此做。

## 公历转中历

本软体套件提供下列三个函数转公历为中历：

- `.western_to_chinese_date(y, m, d, calendar='default', multiple_calendars=False, ephemeris='None')`: 公历日期(年 = y, 月 = m, 日 = d)转中历日期。

- `.western_to_chinese_year(y, m=None, calendar='default', ephemeris='None')`: 公历 y 年 m 月 中所有日期转为中历日期。如果 m 是 None，则将公历年 y 中所有日期转为中历日期。

- `.western_to_chinese_year_html(y, m=None, calendar='default', showJDN=False, ephemeris='None', show_chinese_year_info=True,show_chinese_calendar_info=True)`: 与函数`.western_to_chinese_year(y, m=None, calendar='default', ephemeris='None')`的功能一样，但会输出 HTML 格式的文字。

`calendar`参数用来选取某中历，默认值是'default'，表示预设中历，用者可选择[其他中历网页](https://ytliu0.github.io/ChineseCalendar-python/tutorial/simplified_Chinese/available_calendars.html)列出的中历标记选择其他中历。

`multiple_calendars`参数只有当`calendar`参数是'default'(预设中历)时才有作用。如果`multiple_calendars`设定为`True`，分裂时代的输出中历会列出多个当时行用的中历。

`ephemeris`参数让用者选择用哪个现代历表计算月相和节气时刻，这里只支持'DE431'和'DE441'，默认值是'None'，表示会用已设定的历表，如果还未设定历表，则用默认值'DE441'。

以下指令转公历445年2月25日为北魏行用的历法。根据[其他中历网页](https://ytliu0.github.io/ChineseCalendar-python/tutorial/simplified_Chinese/available_calendars.html)，北魏的日历要用 'WeiZhouSui' 标记。

In [4]:
cal.western_to_chinese_date(445, 2, 25, calendar='WeiZhouSui')

{'Western ymd': [445, 2, 25],
 'Western calendar': '儒略历',
 'JDN': 1883650,
 'Chinese ymd': [445, -1, 3],
 'cyear': 445,
 'cdate': '闰正月初三',
 'sexagenary year': ['乙酉', '鸡', 22],
 'Nday_cmonth': 29,
 'sexagenary date': ['癸亥', 60],
 'Week': ['星期日', 0],
 'period': '南北朝 (420 - 580)',
 'reign/era': '北魏太武帝太平真君六年',
 'Chinese calendar': '景初历'}

函数输出显示公历445年2月25日，在北魏的日历是太武帝太平真君六年闰正月初三，年干支是乙酉、日干支是癸亥，当时北魏行用的历法是景初历。

此函数的输出是 python dictionary，有下列的字典键(keys):

`'Western ymd'`: python list 包含公历的年月日。

`'Western calendar'`: 公历版本 (格里历、儒略历或逆推儒略历)。

`'JDN'`: 正午儒略日数。

`'Chinese ymd'`: 包含中历的年月日，闰月的月份用负数表示。 

`'cyear'`: 与中历年日期重叠最多的公历年份，也是`'Chinese ymd'` list 中第一个数字。此例的太平真君六年就是445年，因为太平真君六年始于445年1月24日，终于446年2月11日，太平真君六年与公历445年有342日重叠，是重叠日数最多的公历年，因此甲辰年的`'cyear'`取445。

`'cdate'`: 中历日期。

`'sexagenary year'`: python list 显示年干支，年地支对应的生肖，及干支数 (1=甲子，2＝乙丑，3＝丙寅等，六十干支的干支数可参阅[干支网页](https://ytliu0.github.io/ChineseCalendar/sexagenary_simp.html)的表二) 。

`'jian'`: 中历月的月建干支，月干支的详情可参阅[干支网页](https://ytliu0.github.io/ChineseCalendar/sexagenary_simp.html)。

`'Nday_cmonth'`: 中历月的日数，一般是29日或30日。

`'sexagenary date'`: 日干支及其干支数，日干支的详情参阅[干支网页](https://ytliu0.github.io/ChineseCalendar/sexagenary_simp.html)。

`'Week'`: 星期及星期数，星期数用 0、1、2、3、4、5、6 表示星期日、一、二、三、四、五、六。 

`'period'`: 中国历史的时代。

`'Chinese calendar'`: 中历的版本。

与我的[农历网站](https://ytliu0.github.io/ChineseCalendar/index_simp.html)一样，公历年 y 的年限是 -721 至 2200。当中国处于分裂时代时常有多个历法同时使用，这里用的指令只提供其中一个版本，其他版本的日期也可以获取，方法是选'calendar'参数为'default'及'multiple_calendars'为True:

In [5]:
cal.western_to_chinese_date(445, 2, 25, multiple_calendars=True)

[{'Western ymd': [445, 2, 25],
  'Western calendar': '儒略历',
  'JDN': 1883650,
  'Chinese ymd': [445, 2, 3],
  'cyear': 445,
  'cdate': '二月初三',
  'sexagenary year': ['乙酉', '鸡', 22],
  'jian': ['建己卯', 16],
  'Nday_cmonth': 29,
  'sexagenary date': ['癸亥', 60],
  'Week': ['星期日', 0],
  'period': '南北朝 (420 - 580)',
  'reign/era': '宋文帝元嘉二十二年',
  'Chinese calendar': '元嘉历'},
 {'Western ymd': [445, 2, 25],
  'Western calendar': '儒略历',
  'JDN': 1883650,
  'Chinese ymd': [445, -1, 3],
  'cyear': 445,
  'cdate': '闰正月初三',
  'sexagenary year': ['乙酉', '鸡', 22],
  'Nday_cmonth': 29,
  'sexagenary date': ['癸亥', 60],
  'Week': ['星期日', 0],
  'period': '南北朝 (420 - 580)',
  'reign/era': '北魏太武帝太平真君六年',
  'Chinese calendar': '景初历'}]

此输出显示公历445年2月25日在刘宋的历法是文帝元嘉二十二年二月初三，当时宋朝行用的历法是元嘉历，此日期就是预设中历输出的日期。

指令`cal.western_to_chinese_year(445, 2, calendar='WeiZhouSui')`输出 python list 包含公历445年2月对应的北魏历法日期；`cal.western_to_chinese_year(445, calendar='WeiZhouSui')` 则输出 python list 包含公历445年全年对应的北魏历法日期。

In [6]:
cal.western_to_chinese_year(445, 2, calendar='WeiZhouSui')

[{'Western ymd': [445, 2, 1],
  'Western calendar': '儒略历',
  'JDN': 1883626,
  'Chinese ymd': [445, 1, 9],
  'cyear': 445,
  'cdate': '正月初九',
  'sexagenary year': ['乙酉', '鸡', 22],
  'jian': ['建戊寅', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['己亥', 36],
  'Week': ['星期四', 4],
  'period': '南北朝 (420 - 580)',
  'reign/era': '北魏太武帝太平真君六年',
  'Chinese calendar': '景初历'},
 {'Western ymd': [445, 2, 2],
  'Western calendar': '儒略历',
  'JDN': 1883627,
  'Chinese ymd': [445, 1, 10],
  'cyear': 445,
  'cdate': '正月初十',
  'sexagenary year': ['乙酉', '鸡', 22],
  'jian': ['建戊寅', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['庚子', 37],
  'Week': ['星期五', 5],
  'period': '南北朝 (420 - 580)',
  'reign/era': '北魏太武帝太平真君六年',
  'Chinese calendar': '景初历'},
 {'Western ymd': [445, 2, 3],
  'Western calendar': '儒略历',
  'JDN': 1883628,
  'Chinese ymd': [445, 1, 11],
  'cyear': 445,
  'cdate': '正月十一',
  'sexagenary year': ['乙酉', '鸡', 22],
  'jian': ['建戊寅', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['辛丑', 38],
 

以上的输出如果用于其后的日历计算或许有用，但对于浏览来说并不是很方便，函数`.western_to_chinese_year_html()`输出的 HTML 文字用`IPython.display.HTML()`的函数处理后，就会得到如[这农历网页](https://ytliu0.github.io/ChineseCalendar/index_simp.html)的表列显示，比较方便浏览。

In [7]:
# 公历445年2月与北魏日历对照
HTML(cal.western_to_chinese_year_html(445, 2, calendar='WeiZhouSui'))

In [8]:
# 显示445年2月的北魏月历，并显示每日的正午儒略日数。
HTML(cal.western_to_chinese_year_html(445, 2, calendar='WeiZhouSui', showJDN=True))

上面列出的月相和二十四节气如[农历网站](https://ytliu0.github.io/ChineseCalendar/index_simp.html)的一样是指用现代方法以喷射推进实验室的 DE441 历表算出，而历书节气指按当时中国历法算出的节气日期。

中国科学院紫金山天文台从 2014年起用 DE421 历表编算天文年历，直至2025年还没有更新历表，不过 DE421 算出的月相和节气时刻与 DE431/DE441 在现代相差甚微。所有用现代历表算出的月相和节气时刻都用东八区时间 UT+8 (UT 在1972年前指 UT1， 1972年到今年指 UTC，未来年份则是预推的 UTC)。

In [9]:
# 用国标 《农历的编算和颁行》 GB/T 33661-2017 算出的2500年年历
HTML(cal.western_to_chinese_year_html(2500, calendar='GBT'))

## 中历转公历

本软体提供以下四个函数可用来转中历为公历：

`.chinese_to_western_date(y, m, d, calendar='default', ephemeris='None')`: 转中历年月日 y, m, d 为公历日期，闰月的 m 值为负数。

`.chinese_year_info(y, calendar='default', ephemeris='None')`: 函数输出中历年 y 的所有中历月初一的公历日期，历书节气，及用现代历表 (DE431 或 DE441) 算出的节气。

`.chinese_year_html(y, calendar='default', ephemeris='None')`: 与上述函数的功能一致，但输出 HTML 文字。

`.chinese_to_western_year(y, m=None, calendar='default', ephemeris='None')`: 列出中历年 y 中历月 m 所有日期的公历日期。如果 m 是 None，则列出中历年全年的公历日期。

`chinese_to_western_year_html(y, m=None, calendar='default', showJDN=False, ephemeris='None', show_chinese_year_info=True, show_chinese_calendar_info=True)`: 与上述函数的功能一致，但输出 HTML 文字。

我的[农历网站](https://ytliu0.github.io/ChineseCalendar/index_simp.html) 并没有网页列出这些函数提供的公历资料，[朔闰表网页](https://ytliu0.github.io/ChineseCalendar/table_simp.html)提供与`.chinese_year_html()`函数相近的资料。

这些函数的用法与公历转中历的函数接近，兹举例展示。

In [10]:
# 转南明永历十五年(1661年)八月十五日为公历
cal.chinese_to_western_date(1661, 8, 15, calendar='SouthernMing')

{'Chinese ymd': [1661, 8, 15],
 'Western ymd': [1661, 9, 8],
 'Western calendar': '格里历',
 'JDN': 2327979,
 'cyear': 1661,
 'cdate': '八月十五',
 'sexagenary year': ['辛丑', '牛', 38],
 'jian': ['建丁酉', 34],
 'Nday_cmonth': 29,
 'sexagenary date': ['壬辰', 29],
 'Week': ['星期四', 4],
 'period': '清 (1645 - 1911)',
 'reign/era': '南明永历十五年',
 'Chinese calendar': '残明大统历'}

输出显示公历日期是1661年9月8日。注意南明的八月十五在这年与清朝时宪历不一致，清世祖顺治十八年八月十五在1661年10月7日，可用`cal.chinese_to_western_date(1661, 8, 15)`验证。

历代中国因历法改革有时会出现中历日期对应两个公历日期的情况，例如762年的五月十二日：

In [11]:
cal.chinese_to_western_date(762, 5, 12)

[{'Chinese ymd': [762, 5, 12],
  'Western ymd': [762, 4, 10],
  'Western calendar': '儒略历',
  'JDN': 1999478,
  'cyear': 762,
  'cdate': '五月十二',
  'sexagenary year': ['壬寅', '虎', 39],
  'jian': ['建甲辰', 41],
  'Nday_cmonth': 30,
  'sexagenary date': ['辛卯', 28],
  'Week': ['星期六', 6],
  'period': '唐 (618 - 907)',
  'reign/era': '唐肃宗上元三年/宝应元年',
  'Chinese calendar': '五纪历'},
 {'Chinese ymd': [762, 5, 12],
  'Western ymd': [762, 6, 8],
  'Western calendar': '儒略历',
  'JDN': 1999537,
  'cyear': 762,
  'cdate': '五月十二',
  'sexagenary year': ['壬寅', '虎', 39],
  'jian': ['建丙午', 43],
  'Nday_cmonth': 30,
  'sexagenary date': ['庚寅', 27],
  'Week': ['星期二', 2],
  'period': '唐 (618 - 907)',
  'reign/era': '唐肃宗上元三年/宝应元年',
  'Chinese calendar': '五纪历'}]

以下指令显示颛顼历-250年(前251年)的历日资料。

In [12]:
cal.chinese_year_info(-250, calendar='Zhuanxu')

{'cm': [{'cm': 10, 'JDN': 1629685, 'jian': 'NA', 'n': 29},
  {'cm': 11, 'JDN': 1629714, 'jian': 'NA', 'n': 30},
  {'cm': 12, 'JDN': 1629744, 'jian': 'NA', 'n': 29},
  {'cm': 1, 'JDN': 1629773, 'jian': 'NA', 'n': 30},
  {'cm': 2, 'JDN': 1629803, 'jian': 'NA', 'n': 29},
  {'cm': 3, 'JDN': 1629832, 'jian': 'NA', 'n': 30},
  {'cm': 4, 'JDN': 1629862, 'jian': 'NZ', 'n': 29},
  {'cm': 5, 'JDN': 1629891, 'jian': 'NA', 'n': 30},
  {'cm': 6, 'JDN': 1629921, 'jian': 'NA', 'n': 30},
  {'cm': 7, 'JDN': 1629951, 'jian': 'NA', 'n': 29},
  {'cm': 8, 'JDN': 1629980, 'jian': 'NA', 'n': 30},
  {'cm': 9, 'JDN': 1630010, 'jian': 'NA', 'n': 29},
  {'cm': -9, 'JDN': 1630039, 'jian': 'NA', 'n': 30}],
 'calendar': '颛顼历',
 'reign/era': '秦昭襄王五十六年',
 'calst': [('J10', 1629693),
  ('Z10', 1629708),
  ('J11', 1629723),
  ('Z11', 1629739),
  ('J12', 1629754),
  ('Z12', 1629769),
  ('J1', 1629784),
  ('Z1', 1629799),
  ('J2', 1629815),
  ('Z2', 1629830),
  ('J3', 1629845),
  ('Z3', 1629860),
  ('J4', 1629876),
  ('Z

此函数输出 python dictionary，有以下字键：

`'cm'`: python list 含有以下中历资料： \[{'cm':m1, 'JDN':JDN1, 'jian':'jian1', 'n':n1}, {'cm':m2, 'JDN':JDN2, 'jian':'jian2', 'n':n2}, ...\]，'cm' 表示中历月序(负数表示闰月), 'JDN' 表示朔日的正午儒略日数， 'jian' 表示用月建来算的月干支数 ('jian'='1' 表示甲子，'2' 表示乙丑，⋯⋯，'60' 表示癸亥，'NA' 表示中历月没有月建，一般是闰月，但-103年以前的历法因不用无中气置闰也不列月建，'NZ' 表示此月不含中气，这只适用于古六历的月份)，'n' 表示中历月的日数。 此 python list 以 'JDN' 的数值由小至大排序。

`'calendar'`: 中历的版本 (例如 '三统历'， '时宪历' 等)。

`'reign/era'` (只适用于 1912年前的年份): 中历年的年号或皇帝纪年。

`'calst'`: 历书节气 tuples \[(lab1, jdn1), (lab2, jdn2), ...\]， lab1, lab2, ... 是历书节气的标记，例如 'J1' 表示正月节(立春)，'Z4' 表示四月中(小满) 等，jdn1, jdn2, ... 是历书节气的正午儒略日数。

`'datongST'` (只适用于预设中历在1667至1669的中历年): 用大统历算出的节气 \[(lab1, jdn1), (lab2, jdn2), ...\]。康熙六年(1667)至八年(1669)清朝因历狱而复用明朝《大统历》，但后来清朝钦天监编的《御定万年书》试图抹去这段历史，用时宪历追推这几年的节气，但台湾国立故宫博物院的清代档案检索系统藏有这几年的《大清七政经纬躔度时宪历》，显示这几年的节气日期确是符合大统历的推算，而不符合时宪历的推算，所以此处在这几年列出大统历的节气。

`'sterm'`: python list \[\[lab1, info1\], \[lab2, info2\], ...\] 显示用 DE431/DE441历表算出的节气，lab1, lab2, ... 为节气标记，info1, info2, ... 则是 python dictionary，显示节气的日期及 UT+8 时刻。

`'mphase'`: python list \[\[lab1, info1\], \[lab2, info2\], ...\] 显示用 DE431/DE441 历表算出的中历年内所有的月相资料。lab1, lab2, ... 是月相的标记： 'Q0' 是朔，'Q1' 是上弦，'Q2' 是望，'Q3' 是下弦。 info1, info2, ... 是 python dictionary，显示月相的日期及 UT+8 时刻。

此函数输出的 python list 不方便浏览， 函数 `.chinese_year_info_html()` 输出 HTML 文字，可用 `IPython.display.HTML()` 函数将资料以表格形式显示。

In [13]:
# 颛顼历-250年(前251年)的历日资料
HTML(cal.chinese_year_html(-250, calendar='Zhuanxu'))

中历月,朔日,历书节气,DE441节气 (UT+8)
十月小,戊寅11月1日,立冬: 初九 (11月9日)小雪: 廿四 (11月24日),立冬: 十一 (11月11日) 00:05小雪: 廿五 (11月25日) 17:02
十一月大,丁未11月30日,大雪: 初十 (12月9日)冬至: 廿六 (12月25日),大雪: 十一 (12月10日) 09:34冬至: 廿六 (12月25日) 02:50
十二月小,丁丑12月30日,小寒: 十一 (1月9日)大寒: 廿六 (1月24日),小寒: 初十 (1月8日) 21:19大寒: 廿五 (1月23日) 18:03
正月大,丙午1月28日,立春: 十二 (2月8日)雨水: 廿七 (2月23日),立春: 十一 (2月7日) 17:18雨水: 廿六 (2月22日) 19:49
二月小,丙子2月27日,惊蛰: 十三 (3月11日)春分: 廿八 (3月26日),惊蛰: 十二 (3月10日) 01:30春分: 廿七 (3月25日) 10:39
三月大,乙巳3月28日,清明: 十四 (4月10日)谷雨: 廿九 (4月25日),清明: 十三 (4月9日) 22:47谷雨: 廿九 (4月25日) 13:37
四月小(无中气),乙亥4月27日,立夏: 十五 (5月11日),立夏: 十五 (5月11日) 06:22
五月大,甲辰5月26日,小满: 初一 (5月26日)芒种: 十六 (6月10日),小满: 初二 (5月27日) 00:18芒种: 十七 (6月11日) 18:30
六月大,甲戌6月25日,夏至: 初一 (6月25日)小暑: 十六 (7月10日),夏至: 初三 (6月27日) 12:01小暑: 十九 (7月13日) 04:05
七月小,甲辰7月25日,大暑: 初二 (7月26日)立秋: 十七 (8月10日),大暑: 初四 (7月28日) 17:47立秋: 二十 (8月13日) 04:47


In [14]:
# 用国标《农历的编算与颁行》 GB/T 33661-2017 算出的2714年中历
HTML(cal.chinese_year_html(2714, calendar='GBT'))

中历月,朔日,历书节气,DE441节气 (UT+8)
正月小建丙寅,戊午2月7日,雨水: 十三 (2月19日)惊蛰: 廿八 (3月6日),雨水: 十三 (2月19日) 21:34惊蛰: 廿八 (3月6日) 18:01
二月大建丁卯,丁亥3月8日,春分: 十四 (3月21日)清明: 廿九 (4月5日),春分: 十四 (3月21日) 16:43清明: 廿九 (4月5日) 18:15
三月小建戊辰,丁巳4月7日,谷雨: 十四 (4月20日),谷雨: 十四 (4月20日) 22:46
四月小建己巳,丙戌5月6日,立夏: 初一 (5月6日)小满: 十六 (5月21日),立夏: 初一 (5月6日) 06:27小满: 十六 (5月21日) 17:04
五月大建庚午,乙卯6月4日,芒种: 初三 (6月6日)夏至: 十八 (6月21日),芒种: 初三 (6月6日) 06:19夏至: 十八 (6月21日) 21:40
六月小建辛未,乙酉7月4日,小暑: 初四 (7月7日)大暑: 二十 (7月23日),小暑: 初四 (7月7日) 14:20大暑: 二十 (7月23日) 07:41
七月大建壬申,甲寅8月2日,立秋: 初七 (8月8日)处暑: 廿二 (8月23日),立秋: 初七 (8月8日) 00:38处暑: 廿二 (8月23日) 16:38
八月大建癸酉,甲申9月1日,白露: 初八 (9月8日)秋分: 廿三 (9月23日),白露: 初八 (9月8日) 06:37秋分: 廿三 (9月23日) 18:20
九月小建甲戌,甲寅10月1日,寒露: 初九 (10月9日)霜降: 廿四 (10月24日),寒露: 初九 (10月9日) 03:00霜降: 廿四 (10月24日) 08:45
十月大建乙亥,癸未10月30日,立冬: 初十 (11月8日)小雪: 廿五 (11月23日),立冬: 初十 (11月8日) 11:15小雪: 廿五 (11月23日) 11:03


In [15]:
# 辽穆宗应历五年(955年)八月的所有日期
cal.chinese_to_western_year(955, 8, calendar='LiaoJinYuan')

[{'Chinese ymd': [955, 8, 1],
  'Western ymd': [955, 8, 20],
  'Western calendar': '儒略历',
  'JDN': 2070103,
  'cyear': 955,
  'cdate': '八月初一',
  'sexagenary year': ['乙卯', '兔', 52],
  'jian': ['建乙酉', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['丙申', 33],
  'Week': ['星期一', 1],
  'period': '五代 (907 - 959)',
  'reign/era': '辽穆宗应历五年',
  'Chinese calendar': '调元历'},
 {'Chinese ymd': [955, 8, 2],
  'Western ymd': [955, 8, 21],
  'Western calendar': '儒略历',
  'JDN': 2070104,
  'cyear': 955,
  'cdate': '八月初二',
  'sexagenary year': ['乙卯', '兔', 52],
  'jian': ['建乙酉', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['丁酉', 34],
  'Week': ['星期二', 2],
  'period': '五代 (907 - 959)',
  'reign/era': '辽穆宗应历五年',
  'Chinese calendar': '调元历'},
 {'Chinese ymd': [955, 8, 3],
  'Western ymd': [955, 8, 22],
  'Western calendar': '儒略历',
  'JDN': 2070105,
  'cyear': 955,
  'cdate': '八月初三',
  'sexagenary year': ['乙卯', '兔', 52],
  'jian': ['建乙酉', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['戊戌', 35],
  'Week': 

In [16]:
# 辽穆宗应历五年(955年)八月的 HTML 月历表
HTML(cal.chinese_to_western_year_html(955, 8, calendar='LiaoJinYuan'))

`.western_to_chinese_year_html()`函数输出的月相和节气是公历日期，此数输出的则是中历日期。

In [17]:
# 蜀后主延熙十七年(254年)的年历表
HTML(cal.chinese_to_western_year_html(254, calendar='Shu'))

## 月相和二十四节气

`ChineseCalendar_py.sunMoon.sunMoon` class 提供用现代历表算出的月相和二十四节气的 UT+8 日期和时刻，以下指令建立这 class 的实体。

In [18]:
sm = ccal.sunMoon.sunMoon('ChiS')

第一个输入参数 'ChiS' 表示输出的语言是简体中文，其他可选的是 'Eng'(英文)和 'ChiT' (传统中文)。

第二个可输入的参数是 'DE431' 或 'DE441'， 表示计算月相和节气用的历表，默认值是 'DE441'。如前述，紫金山天文台自2014年起用 DE421 历表编算天文年历，直至2025年仍是如此，DE421、DE431及DE441历表算出的月相和节气在距今几十年间差异甚微(DE421 历表的年限是1899年至2053年)，在远古和遥远将来 DE431 和 DE441 算出的时刻虽然差异较大，但仍未超出 TDB 转换 UT1 的估计误差。1929年至2013年中历的月相和节气用旧历表计算，与 DE 历表的差异可达半分钟。1929年前的节气不但用旧历表计算，时刻也不用UT+8，差异当然更大。

-3502-3503月相与节气的TDB时刻已预先算好，数据存于源码资料夹`src/ChineseCalendar_py/sunMoon_DE431.csv`和`src/ChineseCalendar_py/sunMoon_DE441.csv`。在源码资料夹`src/ChineseCalendar_py/`有函数`get_dTT_UT()`输出 TT-UT 的数值，用于转月相和节气时刻为UT+8，此函数大约一年要更新一次以含括最新闰秒数据，因闰秒将于2035年或更早会被取消，到时便不用频繁更新。

In [19]:
# 获取公元3500年的节气和月相
st, mp = sm.st_mp(3500)
print('节气:\n', st)
print('月相:\n', mp)

节气:
 [['J12', {'event': '小寒', 'year': 3500, 'month': 1, 'date': 6, 'hour': 7, 'minute': 2, 'dateString': '1月6日', 'timeString': '07:02', 'jd0_ut': 2999407.5, 'jd1_ut': 5.959842061353328}], ['Z12', {'event': '大寒', 'year': 3500, 'month': 1, 'date': 21, 'hour': 1, 'minute': 14, 'dateString': '1月21日', 'timeString': '01:14', 'jd0_ut': 2999407.5, 'jd1_ut': 20.718280931005655}], ['J1', {'event': '立春', 'year': 3500, 'month': 2, 'date': 4, 'hour': 18, 'minute': 54, 'dateString': '2月4日', 'timeString': '18:54', 'jd0_ut': 2999407.5, 'jd1_ut': 35.454193554548816}], ['Z1', {'event': '雨水', 'year': 3500, 'month': 2, 'date': 19, 'hour': 12, 'minute': 59, 'dateString': '2月19日', 'timeString': '12:59', 'jd0_ut': 2999407.5, 'jd1_ut': 50.20746779877934}], ['J2', {'event': '惊蛰', 'year': 3500, 'month': 3, 'date': 6, 'hour': 8, 'minute': 1, 'dateString': '3月6日', 'timeString': '08:01', 'jd0_ut': 2999407.5, 'jd1_ut': 65.00048394186084}], ['Z2', {'event': '春分', 'year': 3500, 'month': 3, 'date': 21, 'hour': 4, 'min

In [20]:
# 公元3500年的全年的月相和节气，转为 pandas dataframe 来显示。
st, mp = sm.st_mp_df(3500)
display(st)
display(mp)

,节气,时刻 (UT+8)
0,小寒,"1月6日, 07:02"
1,大寒,"1月21日, 01:14"
2,立春,"2月4日, 18:54"
3,雨水,"2月19日, 12:59"
4,惊蛰,"3月6日, 08:01"
5,春分,"3月21日, 04:53"
6,清明,"4月5日, 03:57"
7,谷雨,"4月20日, 05:50"
8,立夏,"5月5日, 10:38"
9,小满,"5月20日, 18:32"


,朔,上弦,望,下弦
0,,"1月1日, 00:36","1月9日, 03:40<br /><a href=""http://ytliu.epizy.c...","1月17日, 01:05"
1,"1月23日, 17:03","1月30日, 17:13","2月7日, 22:50","2月15日, 12:02"
2,"2月22日, 04:24","3月1日, 12:54","3月9日, 15:55","3月16日, 20:48"
3,"3月23日, 16:24","3月31日, 09:59","4月8日, 06:10","4月15日, 04:01"
4,"4月22日, 05:25","4月30日, 06:15","5月7日, 17:43","5月14日, 10:39"
5,"5月21日, 19:42","5月29日, 23:57","6月6日, 03:04<br /><a href=""http://ytliu.epizy.c...","6月12日, 17:47"
6,"6月20日, 11:01<br /><a href=""http://ytliu.epizy....","6月28日, 14:21","7月5日, 10:52","7月12日, 02:33"
7,"7月20日, 02:39","7月28日, 01:35","8月3日, 17:50","8月10日, 13:55"
8,"8月18日, 17:49","8月26日, 10:14","9月2日, 00:56","9月9日, 04:21"
9,"9月17日, 08:03","9月24日, 17:04","10月1日, 09:19","10月8日, 21:42"


月相中朔和望还提供日月食的资料，有连结到我制的日月食网页，要恰当显示连结，可用 pandas dataframe 提供的 `.to_html` 函数转为 HTML 文字，然后用 `IPython.display.HTML()` 显示，得出的输出类此[气朔网页](https://ytliu0.github.io/ChineseCalendar/sunMoon_simp.html)的表格。

In [21]:
HTML(mp.to_html(
    render_links=True,
    escape=False,
))

,朔,上弦,望,下弦
0,,"1月1日, 00:36","1月9日, 03:40半影月食","1月17日, 01:05"
1,"1月23日, 17:03","1月30日, 17:13","2月7日, 22:50","2月15日, 12:02"
2,"2月22日, 04:24","3月1日, 12:54","3月9日, 15:55","3月16日, 20:48"
3,"3月23日, 16:24","3月31日, 09:59","4月8日, 06:10","4月15日, 04:01"
4,"4月22日, 05:25","4月30日, 06:15","5月7日, 17:43","5月14日, 10:39"
5,"5月21日, 19:42","5月29日, 23:57","6月6日, 03:04月偏食","6月12日, 17:47"
6,"6月20日, 11:01日环食","6月28日, 14:21","7月5日, 10:52","7月12日, 02:33"
7,"7月20日, 02:39","7月28日, 01:35","8月3日, 17:50","8月10日, 13:55"
8,"8月18日, 17:49","8月26日, 10:14","9月2日, 00:56","9月9日, 04:21"
9,"9月17日, 08:03","9月24日, 17:04","10月1日, 09:19","10月8日, 21:42"


## 历书节气

古代的节气用当时的历法计算，算出的节气与用现代历表的节气常有大差异，函数`.calendrical_solar_terms(y, calendar='default', ephemeris='None')`提供公历 y 年的历书节气，即按当时历法计算的节气。参数`ephemeris`只有当选取 calendar='GBT' 时用来选择DE历表，其他的calendar选项没有作用。

In [22]:
# 吴大帝赤乌十三年(250年)的历书节气
cal.calendrical_solar_terms(250, calendar='Wu')

[{'节气': '小寒', '日期': '1月8日'},
 {'节气': '大寒', '日期': '1月23日'},
 {'节气': '立春', '日期': '2月7日'},
 {'节气': '雨水', '日期': '2月22日'},
 {'节气': '惊蛰', '日期': '3月9日'},
 {'节气': '春分', '日期': '3月25日'},
 {'节气': '清明', '日期': '4月9日'},
 {'节气': '谷雨', '日期': '4月24日'},
 {'节气': '立夏', '日期': '5月9日'},
 {'节气': '小满', '日期': '5月25日'},
 {'节气': '芒种', '日期': '6月9日'},
 {'节气': '夏至', '日期': '6月24日'},
 {'节气': '小暑', '日期': '7月9日'},
 {'节气': '大暑', '日期': '7月24日'},
 {'节气': '立秋', '日期': '8月9日'},
 {'节气': '处暑', '日期': '8月24日'},
 {'节气': '白露', '日期': '9月8日'},
 {'节气': '秋分', '日期': '9月23日'},
 {'节气': '寒露', '日期': '10月9日'},
 {'节气': '霜降', '日期': '10月24日'},
 {'节气': '立冬', '日期': '11月8日'},
 {'节气': '小雪', '日期': '11月23日'},
 {'节气': '大雪', '日期': '12月8日'},
 {'节气': '冬至', '日期': '12月24日'}]

In [23]:
# 吴大帝赤乌十三年(250年)的历书节气转为 pandas dataframe 显示
display(pd.DataFrame(cal.calendrical_solar_terms(250, calendar='Wu')))

,节气,日期
0,小寒,1月8日
1,大寒,1月23日
2,立春,2月7日
3,雨水,2月22日
4,惊蛰,3月9日
5,春分,3月25日
6,清明,4月9日
7,谷雨,4月24日
8,立夏,5月9日
9,小满,5月25日


此函数输出公历 y 年的历书节气，如要中历 y 年的历书节气，可用上述
`.chinese_year_info()` 或 `.chinese_year_html()` 函数。

## 日历计算习题

上面介绍了本软体套件提供的公历-中历互转基本函数。本资料夹中`calendar_exercises.ipynb`笔记本会展示如何用本软体提供的函数处理较复杂的日历计算。