# Tutorial

This tutorial provides more information on the functions of this package. It is useful to go through the Quickstart guide first before reading this tutorial. Examples shown in the Quickstart guide will not be repeated here.

## Installation

Use the following `pip` command to install and update this package.

In [1]:
# Uncomment the following line to install and update the package.
#pip install --upgrade ChineseCalendar_py

## Load package

In [2]:
import ChineseCalendar_py.calendar_conversion as ccal
from IPython.display import HTML
import pandas as pd

Use the following command to create an instance of the Chinese calendar object. The input parameter `'Eng'` means the calendar information will be displayed in English. Two other possible parameters are `'ChiT'` for traditional Chinese and `'ChiS'` for simplified Chinese.

In [3]:
cal = ccal.calendar_conversion('Eng')

## Default and Available Calendars

Over the course of Chinese history, there were periods where multiple Chinese calendars were used in different regions in China. This package supports multiple, but not all, versions of Chinese calendars in those periods. 

To prevent confusion, one set of Chinese calendars is selected in those periods used by particular states/regions. This is called the *default calendars* here. In the past, those states were regarded as the legitimate governments representing China by some Chinese historians. Today they are regarded as just conventions with no legitimacy connotation. The [defaule calendar page](https://ytliu0.github.io/ChineseCalendar-python/tutorial/English/default_calendar.html) lists the versions of Chinese calendars selected by the default calendar, which covers the years from -721 (722 BCE) to 2200.

As stated on the [defaule calendar page](https://ytliu0.github.io/ChineseCalendar-python/tutorial/English/default_calendar.html), the calendar data in -103 – 2200 are stored in an array for table lookup. The data are stored in the source-code folder in the file 'default_calendar_M105_2201.csv', which contains the conjunction dates, leap month information and calendrical solar terms counted from Jan 0 of the year. When an instance of the Chinese calendar class is created, the conjunction and leap month information are loaded to the `.calData` array and the calendrical solar term data are loaded to the `calSterm` array. These arrays may be useful in some calendar calculations, as shown in the calendar exercise notebook in this folder. The year span in the arrays are actually from -105 to 2202 for the convenience of calendar calculations.

Apart from the calendars used by the default calendars, this package also supports a number of other version of Chinese calendars. The [available calendar page](https://ytliu0.github.io/ChineseCalendar-python/tutorial/English/available_calendars.html) lists all supported calendars. Note that all the calendars there were used in certain period and certain regions in China. Most of them are calculated based on their calendar rules and can in principle be used outside the years of usage, but it is strongly discouraged to do so.

## Western calendar to Chinese calendar conversion

Three methods are provides to do the conversion:

- `.western_to_chinese_date(y, m, d, calendar=default, multiple_calendars=False, ephemeris='None')`: Western date (year = y, month = m, date = d) to Chinese date.

- `.western_to_chinese_year(y, m=None, calendar='default', ephemeris='None')`: Western year y, month m (if m is not None) to Chinese dates

- `.western_to_chinese_year_html(y, m=None, calendar='default', showJDN=False, ephemeris='None', show_chinese_year_info=True,show_chinese_calendar_info=True)`: Same as `western_to_chinese_year()` but return an HTML text.

The 'multiple_calendars' argument in `.western_to_chinese_date()` is only for the default calendars. If set to True, it will return the dates from multiple Chinese calendars in the periods when China was divided.

The 'calendar' argument allows the user to select a particular Chinese calendar. It's either 'default' (for the default calendars) or one of the calendar labels listed on the [available calendar page](https://ytliu0.github.io/ChineseCalendar-python/tutorial/English/available_calendars.html).

The 'ephemeris' argument allows a user to specify an ephemeris for the times of modern moon phases and solar terms. It's either DE441 or DE431. When the argument is missing, it will take the default value 'None', which will pick whatever ephemeris previously specified or DE441 if an ephemeris has not been specified.

The following command converts February 25, 445 to the Chinese calendar used in the Northern Wei dynasty. According to the [available calendar page](https://ytliu0.github.io/ChineseCalendar-python/tutorial/English/available_calendars.html), we need to use the 'WeiZhouSui' label.

In [4]:
cal.western_to_chinese_date(445, 2, 25, calendar='WeiZhouSui')

{'Western ymd': [445, 2, 25],
 'Western calendar': 'Julian',
 'JDN': 1883650,
 'Chinese ymd': [445, -1, 3],
 'cyear': 445,
 'cdate': 'leap 1-03',
 'sexagenary year': ['Yi You', 'Chicken', 22],
 'Nday_cmonth': 29,
 'sexagenary date': ['Gui Hai', 60],
 'Week': ['Sun', 0],
 'period': 'Northern and Southern Dynasties (420 - 580)',
 'reign/era': '[Northern Wei] Tàiwǔdì Tàipíngzhēnjūn 6',
 'Chinese calendar': 'Jingchu'}

This shows that February 25, 445 corresponds to the 3rd day in the leap month 1 in the Northern Wei calendar, which was based on the Jingchu system. The Chinese year was Tàiwǔdì Tàipíngzhēnjūn 6 and its sexagenary year cycle was Yi You.

This method `.western_to_chinese_date()` returns a python dictionary with the following keys:

`'Western ymd'`: a list containing Western year, month, day

`'Western calendar'`: version of the Western calendar (Gregorian, Julian or propleptic Julian).

`'JDN'`: Julian date at noon. 

`'Chinese ymd'`: a list containing Chinese year, month (negative means leap month) and date. 

`'cyear'`: Western year with the most overlap of days in the Chinese year.

`'cdate'`: Chinese month number-day number. 

`'sexagenary year'`: a list with \[sexagenary year cycle, sexagenary number\]. Sexagenary number 1 means Jia zi, 2 means Yi chow, and so on (see Table 2 on [my sexagenary cycle page](https://ytliu0.github.io/ChineseCalendar/sexagenary.html) for the complete list). 

`'jian'`: sexagenary month cycle. See [my sexagenary cycle page](https://ytliu0.github.io/ChineseCalendar/sexagenary.html) for an explanation of the sexagenary month cycle and *jian*.

`'Nday_cmonth'`: number of days in the Chinese month, usually 29 or 30.

`'sexagenary date'`: sexagenary date cycle. See [my sexagenary cycle page](https://ytliu0.github.io/ChineseCalendar/sexagenary.html) for an explanation of the sexagenary date cycle.

`'Week'`: \[day of week, week number\]. Week number convention: 0 for Sunday, 1 for Monday, 2 for Tuesday, 3 for Wednesday, 4 for Thursday, 5 for Friday and 6 for Saturday.

`'period'`: Period in the Chinese history.

`'Chinese calendar'`: version of the Chinese calendar.

As in [my Chinese calendar webpage](https://ytliu0.github.io/ChineseCalendar), the year y should be between -721 and 2200. In some years in the past, there were multiple versions of Chinese calendar used in those years, and the command returns only one of them. Multiple versions of calendar dates can be retrieved by setting calendar='default' and multiple_calendars=True:

In [5]:
cal.western_to_chinese_date(445, 2, 25, multiple_calendars=True)

[{'Western ymd': [445, 2, 25],
  'Western calendar': 'Julian',
  'JDN': 1883650,
  'Chinese ymd': [445, 2, 3],
  'cyear': 445,
  'cdate': '2-03',
  'sexagenary year': ['Yi You', 'Chicken', 22],
  'jian': ['Ji Mao', 16],
  'Nday_cmonth': 29,
  'sexagenary date': ['Gui Hai', 60],
  'Week': ['Sun', 0],
  'period': 'Northern and Southern Dynasties (420 - 580)',
  'reign/era': '[Song] Wéndì Yuánjiā 22',
  'Chinese calendar': 'Yuanjia'},
 {'Western ymd': [445, 2, 25],
  'Western calendar': 'Julian',
  'JDN': 1883650,
  'Chinese ymd': [445, -1, 3],
  'cyear': 445,
  'cdate': 'leap 1-03',
  'sexagenary year': ['Yi You', 'Chicken', 22],
  'Nday_cmonth': 29,
  'sexagenary date': ['Gui Hai', 60],
  'Week': ['Sun', 0],
  'period': 'Northern and Southern Dynasties (420 - 580)',
  'reign/era': '[Northern Wei] Tàiwǔdì Tàipíngzhēnjūn 6',
  'Chinese calendar': 'Jingchu'}]

This output shows that February 25, 445 also corresponds to the 3rd day in the second month in the calendar used by the Song dynasty, which was based on the Yuanjia system. This is the date that is returned for calendar='default'.

The following command `cal.western_to_chinese_year(445, 2, calendar='WeiZhouSui')` returns a list of dictaionary showing all dates in February 445 in the Northern Wei calendar. The command `cal.western_to_chinese_year(445, calendar='WeiZhouSui')` shows all dates in 445.

In [6]:
cal.western_to_chinese_year(445, 2, calendar='WeiZhouSui')

[{'Western ymd': [445, 2, 1],
  'Western calendar': 'Julian',
  'JDN': 1883626,
  'Chinese ymd': [445, 1, 9],
  'cyear': 445,
  'cdate': '1-09',
  'sexagenary year': ['Yi You', 'Chicken', 22],
  'jian': ['Wu Yin', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['Ji Hai', 36],
  'Week': ['Thu', 4],
  'period': 'Northern and Southern Dynasties (420 - 580)',
  'reign/era': '[Northern Wei] Tàiwǔdì Tàipíngzhēnjūn 6',
  'Chinese calendar': 'Jingchu'},
 {'Western ymd': [445, 2, 2],
  'Western calendar': 'Julian',
  'JDN': 1883627,
  'Chinese ymd': [445, 1, 10],
  'cyear': 445,
  'cdate': '1-10',
  'sexagenary year': ['Yi You', 'Chicken', 22],
  'jian': ['Wu Yin', 15],
  'Nday_cmonth': 30,
  'sexagenary date': ['Geng Zi', 37],
  'Week': ['Fri', 5],
  'period': 'Northern and Southern Dynasties (420 - 580)',
  'reign/era': '[Northern Wei] Tàiwǔdì Tàipíngzhēnjūn 6',
  'Chinese calendar': 'Jingchu'},
 {'Western ymd': [445, 2, 3],
  'Western calendar': 'Julian',
  'JDN': 1883628,
  'Chinese ymd': [

The list above may be useful for further calendar calculations but is not convenient to view. The method `.western_to_chinese_year_html()` returns an html text, which can be displayed nicely in a Jupyter notebook using the `IPython.display.HTML()` function. The result is similar to the calendar table on [my Chinese calendar webpage](https://ytliu0.github.io/ChineseCalendar).

In [7]:
# Calendar table for February, 445 in the Northern Wei calendar
HTML(cal.western_to_chinese_year_html(445, 2, calendar='WeiZhouSui'))

In [8]:
# Showing the JDN (Julian date at noon) in the calendar table February, 445 
# in the Northern Wei calendar
HTML(cal.western_to_chinese_year_html(445, 2, calendar='WeiZhouSui', showJDN=True))

As in [my Chinese calendar page](https://ytliu0.github.io/ChineseCalendar), moon phases and solar terms refer to the modern calculation using JPL's DE441 ephemeris, whereas calendrical solar terms refer to the solar terms calculated using the method at that time. Starting from 2014 and as of 2025, the official moon phases and solar terms promulgated by the Purple Mountain Observatory (the calendrical moon phases and solar terms of modern times) are computed using JPL's DE421/LE421, which are very close to our results based on DE441. All times calculated by DE431/DE441 are in UT+8 (UT1+8 for years before 1972, UTC+8 for years between 1972 and present year, and projected UTC+8 for future years).

In [9]:
# Show the calenar table for 2500 computed by GB/T 33661-2017.
HTML(cal.western_to_chinese_year_html(2500, calendar='GBT'))

## Chinese calendar to Western calendar conversion

Four methods are provided to do the conversion:

`.chinese_to_western_date(y, m, d, calendar='default', ephemeris='None')`: Given a Chinese date (year = y, month = m, date = d), convert to the date in the Western calendar. For a leap month, enter a negative number for `m`.

`.chinese_year_info(y, calendar='default', ephemeris='None')`: Given a Chinese year whose New Year day is closest to Jan 1, y in the Western calendar, this function returns a list containing the first days in Chinese months, calendrical solar terms and solar terms computed by a DE ephemeris in the Chinese year.

`.chinese_year_html(y, calendar='default', ephemeris='None')`: Same as the previous function but returns an HTML text.

`.chinese_to_western_year(y, m=None, calendar='default', ephemeris='None')`: Given a Chinese year y, return a list containing the Western dates corresponding to all days in the year if m is None or Western dates corresponding to all days in month m in the Western calendar.

`chinese_to_western_year_html(y, m=None, calendar='default', showJDN=False, ephemeris='None', show_chinese_year_info=True, show_chinese_calendar_info=True)`: Same as the previous function but returns an HTML text.

There are no equivalent pages in [my Chinese calendar website](https://ytliu0.github.io/ChineseCalendar) providing the same information as these functions. The closest one is the [conversion table page](https://ytliu0.github.io/ChineseCalendar/table.html), which provides information similar to the function `.chinese_year_html()`. 

The usage of these functions are similar to the functions for the conversion from Western to Chinese calendar. Below I show a few examples.

In [10]:
# Convert the 15th day in the 8th month in Chinese year 1661 in the Southern Ming dynasty 
# to Western date
cal.chinese_to_western_date(1661, 8, 15, calendar='SouthernMing')

{'Chinese ymd': [1661, 8, 15],
 'Western ymd': [1661, 9, 8],
 'Western calendar': 'Gregorian',
 'JDN': 2327979,
 'cyear': 1661,
 'cdate': '8-15',
 'sexagenary year': ['Xin Chou', 'Ox', 38],
 'jian': ['Ding You', 34],
 'Nday_cmonth': 29,
 'sexagenary date': ['Ren Chen', 29],
 'Week': ['Thu', 4],
 'period': 'Qing (1645 - 1911)',
 'reign/era': '[Southern Ming] Yǒnglì  15',
 'Chinese calendar': 'Canming Datong'}

This shows that the Western date was September 8, 1661. Note that this was not the date in the calendar used by the Qing dynasty, which was October 7, 1661 as shown by the command `cal.chinese_to_western_date(1661, 8, 15)`.

Ocassionally there are multiple days corresponding to the same Chinese date in the past. This is caused by a Chinese calendar reform. As an example, let's look at the 12th day in the 5th month in the Chinese year 762.

In [11]:
cal.chinese_to_western_date(762, 5, 12)

[{'Chinese ymd': [762, 5, 12],
  'Western ymd': [762, 4, 10],
  'Western calendar': 'Julian',
  'JDN': 1999478,
  'cyear': 762,
  'cdate': '5-12',
  'sexagenary year': ['Ren Yin', 'Tiger', 39],
  'jian': ['Jia Chen', 41],
  'Nday_cmonth': 30,
  'sexagenary date': ['Xin Mao', 28],
  'Week': ['Sat', 6],
  'period': 'Tang (618 - 907)',
  'reign/era': '[Tang] Sùzōng Shàngyuán 3/Bǎoyìng 1',
  'Chinese calendar': 'Wuji'},
 {'Chinese ymd': [762, 5, 12],
  'Western ymd': [762, 6, 8],
  'Western calendar': 'Julian',
  'JDN': 1999537,
  'cyear': 762,
  'cdate': '5-12',
  'sexagenary year': ['Ren Yin', 'Tiger', 39],
  'jian': ['Bing Wu', 43],
  'Nday_cmonth': 30,
  'sexagenary date': ['Geng Yin', 27],
  'Week': ['Tue', 2],
  'period': 'Tang (618 - 907)',
  'reign/era': '[Tang] Sùzōng Shàngyuán 3/Bǎoyìng 1',
  'Chinese calendar': 'Wuji'}]

The following command returns the information of the Chinese year -250 (251 BCE) in the Zhuanxu calendar.

In [12]:
cal.chinese_year_info(-250, calendar='Zhuanxu')

{'cm': [{'cm': 10, 'JDN': 1629685, 'jian': 'NA', 'n': 29},
  {'cm': 11, 'JDN': 1629714, 'jian': 'NA', 'n': 30},
  {'cm': 12, 'JDN': 1629744, 'jian': 'NA', 'n': 29},
  {'cm': 1, 'JDN': 1629773, 'jian': 'NA', 'n': 30},
  {'cm': 2, 'JDN': 1629803, 'jian': 'NA', 'n': 29},
  {'cm': 3, 'JDN': 1629832, 'jian': 'NA', 'n': 30},
  {'cm': 4, 'JDN': 1629862, 'jian': 'NZ', 'n': 29},
  {'cm': 5, 'JDN': 1629891, 'jian': 'NA', 'n': 30},
  {'cm': 6, 'JDN': 1629921, 'jian': 'NA', 'n': 30},
  {'cm': 7, 'JDN': 1629951, 'jian': 'NA', 'n': 29},
  {'cm': 8, 'JDN': 1629980, 'jian': 'NA', 'n': 30},
  {'cm': 9, 'JDN': 1630010, 'jian': 'NA', 'n': 29},
  {'cm': -9, 'JDN': 1630039, 'jian': 'NA', 'n': 30}],
 'calendar': 'Zhuanxu',
 'reign/era': '[Qin] Zhāoxiāngwáng 56',
 'calst': [('J10', 1629693),
  ('Z10', 1629708),
  ('J11', 1629723),
  ('Z11', 1629739),
  ('J12', 1629754),
  ('Z12', 1629769),
  ('J1', 1629784),
  ('Z1', 1629799),
  ('J2', 1629815),
  ('Z2', 1629830),
  ('J3', 1629845),
  ('Z3', 1629860),
  ('J4

The function returns a python list with the following keys:

`'cm'`: a list containing the information of all Chinese months in the form of \[{'cm':m1, 'JDN':JDN1, 'jian':'jian1', 'n':n1}, {'cm':m2, 'JDN':JDN2, 'jian':'jian2', 'n':n2}, ...\] with 'cm' indicating the Chinese month number (negative for a leap month), 'JDN' indicating the Julian date at noon of the first day of the Chinese month, 'jian' indicating the sexagenary month cycle associated with jian ('jian'='1' for jia zi, '2' for yi chou, ... '60' for gui hai, 'NA' for months without jian (leap months or months before -103 when no Zhongqi rule was not imposed), 'NZ' for a month not containing a major solar term (only for the ancient six calendars)), and 'n' indicating the number of days in the Chinese month. The list is sorted in ascending order in the values in 'JDN'.

`'calendar'`: version of the Chinese calendar (e.g. 'Santong', 'Shixian').

`'reign/era'` (optional): reign and/or era name of the Chinese year (only for years before 1912).

`'calst'`: list of tuples \[(lab1, jdn1), (lab2, jdn2), ...\] where lab1, lab2, ... are the lables of the calendrical solar terms (e.g. 'J1', 'Z4') and jdn1, jdn2, ... are the Julian dates at noon of the solar terms.

`'datongST'` (optional): list of tuples \[(lab1, jdn1), (lab2, jdn2), ...\] of all the Datong solar terms in the Chinese year. This is only present for 1667 <= y <= 1669.

`'sterm'`: a list \[\[lab1, info1\], \[lab2, info2\], ...\] containing all solar terms based on DE431/DE441 in Chinese year y, where lab1, lab2, ... are the labels of the solar terms (e.g. 'J8', 'Z3') and info1, info2, ... are dictionaries containing the Western date and time information of the solar terms.

`'mphase'`: a list \[\[lab1, info1\], \[lab2, info2\], ...\] containing all moon phases based on DE431/DE441 in year y, where lab1, lab2, ... are the labels of the moon phases (e.g. 'Q0', 'Q3') and info1, info2, ... are dictionaries containing the Western date and time information of the moon phases.

The returned python list is not convenient for viewing. The `.chinese_year_info_html()` method geneartes an HTML text for a table, which can be viewed in the Jupyter notebook using `IPython.display.HTML()` function.

In [13]:
# Chinese year -250 in the Zhuanxu calendar
HTML(cal.chinese_year_html(-250, calendar='Zhuanxu'))

ChineseMonth,ConjunctionDay,Calendrical Solar Terms,DE441 Solar Term (UT+8)
10 (S),Wu YinNov 1,J10: 9 (Nov 9)Z10: 24 (Nov 24),J10: 11 (Nov 11) 00:05Z10: 25 (Nov 25) 17:02
11 (L),Ding WeiNov 30,J11: 10 (Dec 9)Z11 (Dec. solstice): 26 (Dec 25),J11: 11 (Dec 10) 09:34Z11 (Dec. solstice): 26 (Dec 25) 02:50
12 (S),Ding ChouDec 30,J12: 11 (Jan 9)Z12: 26 (Jan 24),J12: 10 (Jan 8) 21:19Z12: 25 (Jan 23) 18:03
1 (L),Bing WuJan 28,J1: 12 (Feb 8)Z1: 27 (Feb 23),J1: 11 (Feb 7) 17:18Z1: 26 (Feb 22) 19:49
2 (S),Bing ZiFeb 27,J2: 13 (Mar 11)Z2 (March equinox): 28 (Mar 26),J2: 12 (Mar 10) 01:30Z2 (March equinox): 27 (Mar 25) 10:39
3 (L),Yi SiMar 28,J3: 14 (Apr 10)Z3: 29 (Apr 25),J3: 13 (Apr 9) 22:47Z3: 29 (Apr 25) 13:37
4 (S)(no Zhongqi),Yi HaiApr 27,J4: 15 (May 11),J4: 15 (May 11) 06:22
5 (L),Jia ChenMay 26,Z4: 1 (May 26)J5: 16 (Jun 10),Z4: 2 (May 27) 00:18J5: 17 (Jun 11) 18:30
6 (L),Jia XuJun 25,Z5 (June solstice): 1 (Jun 25)J6: 16 (Jul 10),Z5 (June solstice): 3 (Jun 27) 12:01J6: 19 (Jul 13) 04:05
7 (S),Jia ChenJul 25,Z6: 2 (Jul 26)J7: 17 (Aug 10),Z6: 4 (Jul 28) 17:47J7: 20 (Aug 13) 04:47


In [14]:
# Chinese year 2714 based on GB/T 33661-2017
HTML(cal.chinese_year_html(2714, calendar='GBT'))

ChineseMonth,ConjunctionDay,Calendrical Solar Terms,DE441 Solar Term (UT+8)
1 (S)Jian: Bing Yin,Wu WuFeb 7,Z1: 13 (Feb 19)J2: 28 (Mar 6),Z1: 13 (Feb 19) 21:34J2: 28 (Mar 6) 18:01
2 (L)Jian: Ding Mao,Ding HaiMar 8,Z2 (March equinox): 14 (Mar 21)J3: 29 (Apr 5),Z2 (March equinox): 14 (Mar 21) 16:43J3: 29 (Apr 5) 18:15
3 (S)Jian: Wu Chen,Ding SiApr 7,Z3: 14 (Apr 20),Z3: 14 (Apr 20) 22:46
4 (S)Jian: Ji Si,Bing XuMay 6,J4: 1 (May 6)Z4: 16 (May 21),J4: 1 (May 6) 06:27Z4: 16 (May 21) 17:04
5 (L)Jian: Geng Wu,Yi MaoJun 4,J5: 3 (Jun 6)Z5 (June solstice): 18 (Jun 21),J5: 3 (Jun 6) 06:19Z5 (June solstice): 18 (Jun 21) 21:40
6 (S)Jian: Xin Wei,Yi YouJul 4,J6: 4 (Jul 7)Z6: 20 (Jul 23),J6: 4 (Jul 7) 14:20Z6: 20 (Jul 23) 07:41
7 (L)Jian: Ren Shen,Jia YinAug 2,J7: 7 (Aug 8)Z7: 22 (Aug 23),J7: 7 (Aug 8) 00:38Z7: 22 (Aug 23) 16:38
8 (L)Jian: Gui You,Jia ShenSep 1,J8: 8 (Sep 8)Z8 (Sep. equinox): 23 (Sep 23),J8: 8 (Sep 8) 06:37Z8 (Sep. equinox): 23 (Sep 23) 18:20
9 (S)Jian: Jia Xu,Jia YinOct 1,J9: 9 (Oct 9)Z9: 24 (Oct 24),J9: 9 (Oct 9) 03:00Z9: 24 (Oct 24) 08:45
10 (L)Jian: Yi Hai,Gui WeiOct 30,J10: 10 (Nov 8)Z10: 25 (Nov 23),J10: 10 (Nov 8) 11:15Z10: 25 (Nov 23) 11:03


In [15]:
# Extract all days in Chinese month 8 in the Chinese year 955 in the calendar used by the Liao dynasty
cal.chinese_to_western_year(955, 8, calendar='LiaoJinYuan')

[{'Chinese ymd': [955, 8, 1],
  'Western ymd': [955, 8, 20],
  'Western calendar': 'Julian',
  'JDN': 2070103,
  'cyear': 955,
  'cdate': '8-01',
  'sexagenary year': ['Yi Mao', 'Rabbit', 52],
  'jian': ['Yi You', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['Bing Shen', 33],
  'Week': ['Mon', 1],
  'period': 'Five Dynasties (907 - 959)',
  'reign/era': '[Liao] Mùzōng Yìnglì 5',
  'Chinese calendar': 'Tiaoyuan'},
 {'Chinese ymd': [955, 8, 2],
  'Western ymd': [955, 8, 21],
  'Western calendar': 'Julian',
  'JDN': 2070104,
  'cyear': 955,
  'cdate': '8-02',
  'sexagenary year': ['Yi Mao', 'Rabbit', 52],
  'jian': ['Yi You', 22],
  'Nday_cmonth': 30,
  'sexagenary date': ['Ding You', 34],
  'Week': ['Tue', 2],
  'period': 'Five Dynasties (907 - 959)',
  'reign/era': '[Liao] Mùzōng Yìnglì 5',
  'Chinese calendar': 'Tiaoyuan'},
 {'Chinese ymd': [955, 8, 3],
  'Western ymd': [955, 8, 22],
  'Western calendar': 'Julian',
  'JDN': 2070105,
  'cyear': 955,
  'cdate': '8-03',
  'sexagenary y

In [16]:
# Create an HTML table for the Chinese month 8 in the Chinese year 955 
# in the calendar used by the Liao dynasty.
HTML(cal.chinese_to_western_year_html(955, 8, calendar='LiaoJinYuan'))

In [17]:
# Create an HTML table for the Chinese year 254
# in the calendar used by the Shu state.
HTML(cal.chinese_to_western_year_html(254, calendar='Shu'))

Unlike `.western_to_chinese_year_html()`, the dates of moon phases and solar terms under each month refer to the dates in the Chinese calendar.

## Moon phases and solar terms

Dates and times of moon phases and solar terms calculated by a modern ephemeris can be obtained from the `ChineseCalendar_py.sunMoon.sunMoon` class. The following commands create an instance of the `sunMoon` object.

In [18]:
sm = ccal.sunMoon.sunMoon('Eng')

The first parameter 'Eng' sets the display language as English. Two other possible parameters are 'ChiT' for traditional Chinese and 'ChiS' for simplified Chinese.

There is an optional second parameter (either 'DE431' or 'DE441') that allows the user to choose an ephemeris. When the second parameter is absent, it takes on the default value 'DE441' for JPL's DE441 ephemeris. for moon phases and solar terms to be JPL's DE441 ephemeris. DE441 and DE431 give practically identical moon phase and solar term times in years within a few hundred years from 2000. As mentioned above, the official moon phases and solar terms promulgated by the Purple Mountain Observatory in 2014-present (as of 2025) are calculated by JPL's DE421/LE421, which also gives practially identical moon phase and solar term times from 2014-present. The moon phases and solar terms promulgated by the government in 1929-2013 were calculated by older ephemerides and could deviate from those of DE431/DE441 by half minutes. Before 1929, moon phases and solar terms not only were calculated by old ephemerides but times were not given in UT+8. 

The TDB times of moon phases and solar terms in -3502-3503 are pre-computed by DE431 and DE441. They are stored in the files 'sunMoon_DE431.csv' and 'sunMoon_DE441.csv' in the folder `src/ChineseCalendar_py/`. Times in UT+8 are converted from the TDB times in the function `get_dTT_UT()` in `src/ChineseCalendar_py/` folder. This function will be updated on a yearly basis to incorporate the most up-to-date leap second data. As leap seconds will be abolished before 2035, the updates will be much less frequent after 2035.

In [19]:
# Extract solar terms and moon phases in 3500 
st, mp = sm.st_mp(3500)
print('solar terms:\n', st)
print('moon phases:\n', mp)

solar terms:
 [['J12', {'event': 'J12', 'year': 3500, 'month': 1, 'date': 6, 'hour': 7, 'minute': 2, 'dateString': 'Jan 6', 'timeString': '07:02', 'jd0_ut': 2999407.5, 'jd1_ut': 5.959842061353328}], ['Z12', {'event': 'Z12', 'year': 3500, 'month': 1, 'date': 21, 'hour': 1, 'minute': 14, 'dateString': 'Jan 21', 'timeString': '01:14', 'jd0_ut': 2999407.5, 'jd1_ut': 20.718280931005655}], ['J1', {'event': 'J1', 'year': 3500, 'month': 2, 'date': 4, 'hour': 18, 'minute': 54, 'dateString': 'Feb 4', 'timeString': '18:54', 'jd0_ut': 2999407.5, 'jd1_ut': 35.454193554548816}], ['Z1', {'event': 'Z1', 'year': 3500, 'month': 2, 'date': 19, 'hour': 12, 'minute': 59, 'dateString': 'Feb 19', 'timeString': '12:59', 'jd0_ut': 2999407.5, 'jd1_ut': 50.20746779877934}], ['J2', {'event': 'J2', 'year': 3500, 'month': 3, 'date': 6, 'hour': 8, 'minute': 1, 'dateString': 'Mar 6', 'timeString': '08:01', 'jd0_ut': 2999407.5, 'jd1_ut': 65.00048394186084}], ['Z2', {'event': 'Z2 (March equinox)', 'year': 3500, 'month'

In [20]:
# Extract solar terms and moon phases in 3500 and put them into pandas df's
st, mp = sm.st_mp_df(3500)
display(st)
display(mp)

,solar term,time (UT+8)
0,J12,"Jan 6, 07:02"
1,Z12,"Jan 21, 01:14"
2,J1,"Feb 4, 18:54"
3,Z1,"Feb 19, 12:59"
4,J2,"Mar 6, 08:01"
5,Z2 (March equinox),"Mar 21, 04:53"
6,J3,"Apr 5, 03:57"
7,Z3,"Apr 20, 05:50"
8,J4,"May 5, 10:38"
9,Z4,"May 20, 18:32"


,New Moon,First Quarter,Full Moon,Last Quarter
0,,"Jan 1, 00:36","Jan 9, 03:40<br /><a href=""http://ytliu.epizy....","Jan 17, 01:05"
1,"Jan 23, 17:03","Jan 30, 17:13","Feb 7, 22:50","Feb 15, 12:02"
2,"Feb 22, 04:24","Mar 1, 12:54","Mar 9, 15:55","Mar 16, 20:48"
3,"Mar 23, 16:24","Mar 31, 09:59","Apr 8, 06:10","Apr 15, 04:01"
4,"Apr 22, 05:25","Apr 30, 06:15","May 7, 17:43","May 14, 10:39"
5,"May 21, 19:42","May 29, 23:57","Jun 6, 03:04<br /><a href=""http://ytliu.epizy....","Jun 12, 17:47"
6,"Jun 20, 11:01<br /><a href=""http://ytliu.epizy...","Jun 28, 14:21","Jul 5, 10:52","Jul 12, 02:33"
7,"Jul 20, 02:39","Jul 28, 01:35","Aug 3, 17:50","Aug 10, 13:55"
8,"Aug 18, 17:49","Aug 26, 10:14","Sep 2, 00:56","Sep 9, 04:21"
9,"Sep 17, 08:03","Sep 24, 17:04","Oct 1, 09:19","Oct 8, 21:42"


Note that links to information on eclipses are provided in the moon phase data. To properly display the links, we can convert the pandas df to html and then use HTML to display the result. The resulting table is similar to my [moon phase and solar term page](https://ytliu0.github.io/ChineseCalendar/sunMoon.html).

In [21]:
HTML(mp.to_html(
    render_links=True,
    escape=False,
))

,New Moon,First Quarter,Full Moon,Last Quarter
0,,"Jan 1, 00:36","Jan 9, 03:40Penumbral lunar eclipse","Jan 17, 01:05"
1,"Jan 23, 17:03","Jan 30, 17:13","Feb 7, 22:50","Feb 15, 12:02"
2,"Feb 22, 04:24","Mar 1, 12:54","Mar 9, 15:55","Mar 16, 20:48"
3,"Mar 23, 16:24","Mar 31, 09:59","Apr 8, 06:10","Apr 15, 04:01"
4,"Apr 22, 05:25","Apr 30, 06:15","May 7, 17:43","May 14, 10:39"
5,"May 21, 19:42","May 29, 23:57","Jun 6, 03:04Partial lunar eclipse","Jun 12, 17:47"
6,"Jun 20, 11:01Annular solar eclipse","Jun 28, 14:21","Jul 5, 10:52","Jul 12, 02:33"
7,"Jul 20, 02:39","Jul 28, 01:35","Aug 3, 17:50","Aug 10, 13:55"
8,"Aug 18, 17:49","Aug 26, 10:14","Sep 2, 00:56","Sep 9, 04:21"
9,"Sep 17, 08:03","Sep 24, 17:04","Oct 1, 09:19","Oct 8, 21:42"


## Calendrical solar terms

Solar terms in the past were not calculated using modern ephemerides, but were calculated using the astronomical systems developed in the past. I call them the calendrical solar terms. The method `.calendrical_solar_terms(y, calendar="default", ephemeris='None')` returns the calendrical solar terms in Western year y. The argument 'ephemeris' is only relevant for the GBT calendar.

In [22]:
# calendrical solar term in 250 in the Wu state
cal.calendrical_solar_terms(250, calendar='Wu')

[{'solar term': 'J12', 'date': 'Jan 8'},
 {'solar term': 'Z12', 'date': 'Jan 23'},
 {'solar term': 'J1', 'date': 'Feb 7'},
 {'solar term': 'Z1', 'date': 'Feb 22'},
 {'solar term': 'J2', 'date': 'Mar 9'},
 {'solar term': 'Z2 (March equinox)', 'date': 'Mar 25'},
 {'solar term': 'J3', 'date': 'Apr 9'},
 {'solar term': 'Z3', 'date': 'Apr 24'},
 {'solar term': 'J4', 'date': 'May 9'},
 {'solar term': 'Z4', 'date': 'May 25'},
 {'solar term': 'J5', 'date': 'Jun 9'},
 {'solar term': 'Z5 (June solstice)', 'date': 'Jun 24'},
 {'solar term': 'J6', 'date': 'Jul 9'},
 {'solar term': 'Z6', 'date': 'Jul 24'},
 {'solar term': 'J7', 'date': 'Aug 9'},
 {'solar term': 'Z7', 'date': 'Aug 24'},
 {'solar term': 'J8', 'date': 'Sep 8'},
 {'solar term': 'Z8 (Sep. equinox)', 'date': 'Sep 23'},
 {'solar term': 'J9', 'date': 'Oct 9'},
 {'solar term': 'Z9', 'date': 'Oct 24'},
 {'solar term': 'J10', 'date': 'Nov 8'},
 {'solar term': 'Z10', 'date': 'Nov 23'},
 {'solar term': 'J11', 'date': 'Dec 8'},
 {'solar term': '

In [23]:
# calendrical solar term in 250 in the Wu state displayed as a pandas df
display(pd.DataFrame(cal.calendrical_solar_terms(250, calendar='Wu')))

,solar term,date
0,J12,Jan 8
1,Z12,Jan 23
2,J1,Feb 7
3,Z1,Feb 22
4,J2,Mar 9
5,Z2 (March equinox),Mar 25
6,J3,Apr 9
7,Z3,Apr 24
8,J4,May 9
9,Z4,May 25


Calendrical solar terms in a Chinese year can be obtained using the method `.chinese_year_info()` or `.chinese_year_html()` shown above.

## Calendar Exercises

The above summarizes the main functions provided by this package. You can see examples of using this package to perform advanced calendar calculations in the `calendar_exercises.ipynb` notebook in this folder.